### ISSUE TITLE
开放注册与关闭注册模板修正

### ISSUE THREAD

**Issue by huaxing211** [wisp-x/lsky-pro#1]
如果关闭了注册，不需要显示注册表单，只显示提示即可：
{if $config.close_register}
  仅提示已关闭注册
{else /}
  显示注册表单信息
{/if}

**Comment by wisp-x** [comment]
目前是关闭注册后，会在注册按钮上加上disabled 属性，当然如果您关闭注册后不想显示表单信息，可自行修改视图。
