### ISSUE TITLE
希望在后台-我的图片-增加“分类管理”功能

### ISSUE THREAD

**Issue by 1424753988** [wisp-x/lsky-pro#10]
类似于新建一个文件夹，然后文件夹里放各类图片。如果所有图片都弄在一块的话，会比较难以管理。已经给你小星星了，这是目前我遇到的最好用的图床，真心谢谢您！

**Comment by 1424753988** [comment]
经过一段时间体验，我觉得这样做会比较好点。
2）同时上传图片的模式建议修改成这种：先上传完成5张图片，然后再上传剩下的。如果所有图片一次性都开始上传的话，服务器会喘不过气的。
3）“我的图片”显示方式可以为列表，如果是缩略图显示，会有点卡顿。

**Comment by wisp-x** [comment]
感谢建议，会针对这方面改进。
