### ISSUE TITLE
这是BUG吗

### ISSUE THREAD

**Issue by klpbbs** [wisp-x/lsky-pro#101]
![image](https://user-images.githubusercontent.com/62373803/77081191-35676180-6a35-11ea-9b68-940382d99bef.png)
首先，这里上传第一个，然后鼠标放上面，就会有红框，然后再接着选择
![image](https://user-images.githubusercontent.com/62373803/77081089-1537a280-6a35-11ea-81db-5422a547b653.png)
鼠标移动到第二个链接时红框竟然跑到第一个去了，，，，

**Comment by wisp-x** [comment]
不算 bug, 目前这个功能只对支持一次性上传的图片有效, 还有, 原文件名称命名规则暂不支持与其他规则组合使用
