### ISSUE TITLE
上传相同图片时，虽然不会重复上传，但首页的图片数量仍然会增加。

### ISSUE THREAD

**Issue by acgbox233** [wisp-x/lsky-pro#102]
## 演示：
- 上传了3张相同的图片
![test.png](https://i.loli.net/2020/03/21/75EsRNHAqcKDkuF.png)
## 问题描述
虽然在网站后台中实际的图片数量并没有增加并且也会返回同一个链接，但是首页显示的`“本站托管图片总数”`仍然会+1
## 环境：
>VPS管理面板：Appnode
>PHP：7.3.13
>MySQL：5.7.23
>Ngnix：1.16.1

**Comment by wisp-x** [comment]
从逻辑上来说, 只要存在一条图片记录, 不管是图片已经是否重复, 都应该是按照记录来, 因为用户并不知道图片已经存在.
