### ISSUE TITLE
升级出现安装包损坏错误

### ISSUE THREAD

**Issue by BatterToMe** [wisp-x/lsky-pro#105]
![image](https://user-images.githubusercontent.com/28335911/77332474-0f0b3400-6d5d-11ea-8db4-8f9100e6afa8.png)

我完全按照更新步骤做的，重新进入网站，发现依然提示要升级，选择在线升级后就出现安装包损坏错误。。

**Comment by wisp-x** [comment]
请按升级指导中的最后一步，使用数据库管理工具导入 update.sql 文件。

**Comment by BatterToMe** [comment]
现在刷新一下页面，重新升级好像有效果了，提示是最新版本了，可能是没有清空缓存的原因
