### ISSUE TITLE
无法删除的bug问题

### ISSUE THREAD

**Issue by kggzs** [wisp-x/lsky-pro#113]
上传的图片，无法通过后台删除

**Comment by wisp-x** [comment]
请表述清楚，哪个版本、提示什么

**Comment by kggzs** [comment]
软件版本： v1.6.0
操作系统： Linux
运行环境：nginx/1.17.8 
PHP 版本： 7.0.33
在图片管理中，点击删除图片无反应
已经给777权限了
网站使用了https
