### ISSUE TITLE
您好，我遇到一个问题需要您的帮助

### ISSUE THREAD

**Issue by 862837706** [wisp-x/lsky-pro#116]
在使用lsky的时候，我添加了要给七牛云的储存位置，但是上传的图片会自动在”文件路径命名规则“与
”文件命名规则“中间添加/字符，但七牛云把他当作一个文件夹的分隔符，导致无法正常读取七牛云中储存的图片。希望您能帮助我，感谢！

**Comment by wisp-x** [comment]
没看懂你想要表达的意思。

**Comment by 862837706** [comment]
但是使用lsky上传图片会自动重命名，必定会添加斜杠


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wisp X"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 晚上7:36
收件人:&nbsp;"wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送:&nbsp;"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<862837706@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wisp-x/lsky-pro] 您好，我遇到一个问题需要您的帮助 (#116)





 
没看懂你想要表达的意思。

**Comment by 862837706** [comment]
是这样的，例如我上传了一张图。
链接是http://862837706.ldq123.xyz/20200416/b4631c2672674.jpeg
打开是无法访问的，因为我用的是七牛云。862837706.ldq123.xyz是我的外链地址，如果链接是这样的862837706.ldq123.xyz/1.jpeg就可以访问。
如果变成多一个 斜杠的符号 /，例如：862837706.ldq123.xyz/2020/1.jpeg七牛云就会判定是这个空间下面的一个文件夹。打开就是404页面。
意思就是我的七牛云储存链接后面只能有一个斜杠然后是文件夹名字点格式，如果图片多一个斜杠就会无法打开外链。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wisp X"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 晚上7:36
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;; 
抄送: "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<862837706@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wisp-x/lsky-pro] 您好，我遇到一个问题需要您的帮助 (#116)





 
没看懂你想要表达的意思。

**Comment by wisp-x** [comment]
还是没懂，是我理解能力太差了还是你没表达清楚？  
你上传成功后为什么无法访问？定义了文件夹以及文件的命名规则后，程序就会根据你命名的规则进行区分文件夹和路径。  
无法访问请检查你访问的路径与七牛云储存中的文件路径是否相符。
