### ISSUE TITLE
腾讯云存储设置了图片处理样式，图床环境变量那里开启样式后，得出来的图片连接会出现两次样式

### ISSUE THREAD

**Issue by jihuoxia** [wisp-x/lsky-pro#118]
我用的腾讯云存储，开启了图片处理样式。图床环境变量那里也开启了 url_query = '-1'
比如应该是这样的连接http://xxx.com/2020/04/19/aaa.jpg-1
上传好以后出现的是http://xxx.com/2020/04/19/aaa.jpg-1-1这样的，-1出现了两次
-是我COS的样式分隔符
1是我的图片处理样式。

是不是BUG

**Comment by wisp-x** [comment]
是 bug，上传时返回的链接会受影响。
