### ISSUE TITLE
希望可以添加***已托管*** 张图片

### ISSUE THREAD

**Issue by logdns** [wisp-x/lsky-pro#12]
希望可以有这个效果 辛苦了,如果有时间的话

![QQ截图20190101193627.jpg](https://tu.my/2019/01/01/5c2b50ec7d618.jpg)

**Comment by wisp-x** [comment]
下个版本将增加。

**Comment by wisp-x** [comment]
@huaxing211 之前主分支是开发版，现已取消，下个版本增加。
