### ISSUE TITLE
使用又怕云USS存储策略上传时报错

### ISSUE THREAD

**Issue by ShaoPak** [wisp-x/lsky-pro#120]
第一次配置好后上传报错，后面又更换了密钥试了很多次，依旧报错，是不支持又拍云https还是什么问题

![image](https://user-images.githubusercontent.com/62377236/79833444-f20a6500-83dd-11ea-8b00-ef62fee399c4.png)

**Comment by wisp-x** [comment]
建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051

**Comment by ShaoPak** [comment]
> 建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051

按着文档试了，还新建了一个云存储，还是不行，注意到教程里的操作员密码是手动输入的，现在又拍云是系统生成的密码，可能是这个原因导致不能用么

**Comment by wisp-x** [comment]
> > 建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051
> 
> 按着文档试了，还新建了一个云存储，还是不行，注意到教程里的操作员密码是手动输入的，现在又拍云是系统生成的密码，可能是这个原因导致不能用么

打开根目录 `.env` 文件，将 `debug = false` 改为 `debug = true`，打开后再试会出现详细的错误信息，将详细错误信息贴上来看一下。

**Comment by ShaoPak** [comment]
> > > 建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051
> > 
> > 
> > 按着文档试了，还新建了一个云存储，还是不行，注意到教程里的操作员密码是手动输入的，现在又拍云是系统生成的密码，可能是这个原因导致不能用么
> 
> 打开根目录 `.env` 文件，将 `debug = false` 改为 `debug = true`，打开后再试会出现详细的错误信息，将详细错误信息贴上来看一下。

Uss：Client error: `PUT http://v0.api.upyun.com/p1-links/2020/04/21/oudeico.png` resulted in a `401 Unauthorized` response:
{"msg":"signature error","code":40100005,"id":"249f191e3a554e5e9cf66f03c410bd8c"}

**Comment by wisp-x** [comment]
> > > > 建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051
> > > 
> > > 
> > > 按着文档试了，还新建了一个云存储，还是不行，注意到教程里的操作员密码是手动输入的，现在又拍云是系统生成的密码，可能是这个原因导致不能用么
> > 
> > 
> > 打开根目录 `.env` 文件，将 `debug = false` 改为 `debug = true`，打开后再试会出现详细的错误信息，将详细错误信息贴上来看一下。
> 
> Uss：Client error: `PUT http://v0.api.upyun.com/p1-links/2020/04/21/oudeico.png` resulted in a `401 Unauthorized` response:
> {"msg":"signature error","code":40100005,"id":"249f191e3a554e5e9cf66f03c410bd8c"}

又拍云接口返回的签名错误提示，检查你填的配置是否正确、是否存在空格之类的。

**Comment by ShaoPak** [comment]
> > > > > 建议按照文档步骤来 https://www.kancloud.cn/wispx/lsky-pro/880051
> > > > 
> > > > 
> > > > 按着文档试了，还新建了一个云存储，还是不行，注意到教程里的操作员密码是手动输入的，现在又拍云是系统生成的密码，可能是这个原因导致不能用么
> > > 
> > > 
> > > 打开根目录 `.env` 文件，将 `debug = false` 改为 `debug = true`，打开后再试会出现详细的错误信息，将详细错误信息贴上来看一下。
> > 
> > 
> > Uss：Client error: `PUT http://v0.api.upyun.com/p1-links/2020/04/21/oudeico.png` resulted in a `401 Unauthorized` response:
> > {"msg":"signature error","code":40100005,"id":"249f191e3a554e5e9cf66f03c410bd8c"}
> 
> 又拍云接口返回的签名错误提示，检查你填的配置是否正确、是否存在空格之类的。
仔细检查了一下没有错误，翻了一下官方文档，大佬可以给看看可能哪方面不对
![image](https://user-images.githubusercontent.com/62377236/79840533-9a252b80-83e8-11ea-921a-a912bff6d482.png)

**Comment by ShaoPak** [comment]
大佬有用又拍云USS试下吗

**Comment by wisp-x** [comment]
> 大佬有用又拍云USS试下吗

刚刚测试了一下，正常

**Comment by ShaoPak** [comment]
> > 大佬有用又拍云USS试下吗
> 
> 刚刚测试了一下，正常

辛苦大佬了，现在正常了，是后台操作员密码必须要点确定才会生效。
