### ISSUE TITLE
请问底部内容是否可以修改

### ISSUE THREAD

**Issue by BobAnkh** [wisp-x/lsky-pro#122]
![image](https://user-images.githubusercontent.com/44333669/80961610-e25b3980-8e3d-11ea-8a9d-608e79e34fae.png)

这里的内容是否可以进行修改？应该如何修改？

**Comment by acgnfeng** [comment]
版权肯定不能删，后面的内容应该可以自由更改
根目录/application/index/view/common/base.html，大概在136行

**Comment by BobAnkh** [comment]
@acgnfeng 
感谢您，我主要是想将后面的内容——违规说明进行一些修改！
