### ISSUE TITLE
开启鉴黄报错 Url not accessible or malformed image

### ISSUE THREAD

**Issue by Creling** [wisp-x/lsky-pro#129]
你好:
开启图片鉴黄且将`intercept_salacity`设置为false后，上传图片时出现Url not accessible or malformed image，关闭图片鉴黄后一切正常。
请问这可能是什么原因？

**Comment by wisp-x** [comment]
鉴黄接口平台无法访问到你的图片就会出现这样的错误

**Comment by Creling** [comment]
但是按照文档说明，当`intercept_salacity`为`false`时，上传图片的行为并不会被拦截，也就是说在这个过程中鉴黄接口应该是不发挥作用的。
