### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by Lulululx** [wisp-x/lsky-pro#130]
大佬安装的时候报错
Warning: require(): open_basedir restriction in effect. File(/www/wwwroot/img/thinkphp/base.php) is not within the allowed path(s): (/www/wwwroot/img/public/:/tmp/:/proc/) in /www/wwwroot/img/public/index.php on line 18

Warning: require(/www/wwwroot/img/thinkphp/base.php): failed to open stream: Operation not permitted in /www/wwwroot/img/public/index.php on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/img/public/../thinkphp/base.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/img/public/index.php on line 18
应该怎么解决？

**Comment by wisp-x** [comment]
关闭防跨站攻击，删除public目录下的.user.ini文件
