### ISSUE TITLE
上传错误：非法的图片文件

### ISSUE THREAD

**Issue by Decem6er** [wisp-x/lsky-pro#131]
我在上传png图片时提示 Upload Error 非法图片文件。另外，我已经关闭图片鉴黄并在系统设置中允许png文件上传。请问这是为什么呢？

**Comment by wisp-x** [comment]
程序框架(thinkphp)会使用内置函数进行校验图片，请检查你的图片是否真的是 PNG 格式，或者进行裁剪、压缩等处理后在上传试试。

**Comment by Decem6er** [comment]
谢谢，我在用系统内置的画图工具进行另存为后能够正常上传了。原来的图片格式确实不是png。
