### ISSUE TITLE
设置页面无法保存

### ISSUE THREAD

**Issue by am-abudu** [wisp-x/lsky-pro#132]
设置页面无法保存，图片上传后链接无法打开，安装时全部绿色√通过

**Comment by am-abudu** [comment]
左下角还有个圈圈一直转，使用apache

**Comment by am-abudu** [comment]
设置运行路径后恢复

**Comment by am-abudu** [comment]
但是依然左下角转圈

**Comment by am-abudu** [comment]
![image.png](https://i.loli.net/2020/05/27/xTtpDnaR4UVONsG.png)

**Comment by wisp-x** [comment]
https://www.kancloud.cn/wispx/lsky-pro/1526363

伪静态配置了吗？文档看了吗？能不能在找不到解决方法的时候在提问？

**Comment by am-abudu** [comment]
配置了伪静态，也没有修改自定义 css 和 js 
伪静态规则如下
`<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_URI} !^/public/
RewriteRule ^(.*)$ /public/$1 [L]
</IfModule>`

**Comment by wisp-x** [comment]
请使用程序中的伪静态，修改运行目录请直接修改站点配置文件，不要使用伪静态来实现。
