### ISSUE TITLE
图片多次上传，images表数据重复，页面展示重复

### ISSUE THREAD

**Issue by rikei** [wisp-x/lsky-pro#135]
![截屏2020-06-10 09.24.56.png](https://img.zaqla.com/2020/06/10/dff4fde801d48.png)

![截屏2020-06-10 09.26.54.png](https://img.zaqla.com/2020/06/10/19fcd4cbd80b6.png)

**Comment by rikei** [comment]
修改了下就不会重复了（其实我不懂php~~）
![](https://img.zaqla.com/2020/06/11/74dc37c70f386.png)

**Comment by wisp-x** [comment]
这个是正常的逻辑，可以看
https://github.com/wisp-x/lsky-pro/blob/bfe9e322aae63b58162b811302c869ffc43ceb18/application/common/controller/Upload.php#L108-L178

108 行到 178 行的逻辑，上传出现相同的图片(md5值相同)，会跳过储存文件的步骤直接“复制”该文件的记录储存起来，这样就能实现多条记录指向同一个文件，节省储存。

删除文件中也做了判断，删除图片时如果有相同 md5 的文件记录，则只删除记录不删除文件(防止两个用户有相同的文件，一个用户删除了该文件导致另一个用户该文件也被删除的情况)。

https://github.com/wisp-x/lsky-pro/blob/bfe9e322aae63b58162b811302c869ffc43ceb18/application/index/controller/User.php#L53-L57
