### ISSUE TITLE
Google浏览器兼容问题，图片下载地址没有展开

### ISSUE THREAD

**Issue by Andy095** [wisp-x/lsky-pro#137]
![image](https://user-images.githubusercontent.com/41384519/84452739-3bae5800-ac89-11ea-9474-c2e1ce8daada.png)

**Comment by wisp-x** [comment]
你这并不是 google chrome

**Comment by Andy095** [comment]
360极速浏览器，谷歌内核，360不正常，谷歌正常

**Comment by wisp-x** [comment]
关掉极速模式再试试

**Comment by Andy095** [comment]
还有一个问题，apache 要怎么安装这个系统， 【Apache 直接使用 .htaccess 即可】 这句话看不懂

**Comment by wisp-x** [comment]
apache 开启了伪静态即可，不需要像 nginx 那样需要手动设置伪静态

**Comment by Andy095** [comment]
后台管理员页面需要在哪里登陆，没有看到入口

**Comment by Andy095** [comment]
直接后台数据库改成管理员了

**Comment by Andy095** [comment]
谢谢问题解决了
