### ISSUE TITLE
希望可以弄一个上传文件类型用户组

### ISSUE THREAD

**Issue by xiaoyi688** [wisp-x/lsky-pro#141]
不同的用户组可以设置上传不同的文件类型

**Comment by wisp-x** [comment]
这是图床，图片类型也就那么多，为什么还要设置不同图片类型的用户组？

**Comment by xiaoyi688** [comment]
未登录用户支持上传小部分图片类型文件(png，jpg)，登录后可以上传全部类型




---原始邮件---
发件人: "Wisp X"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 下午4:08
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "xiaoyi688"<2531170283@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] 希望可以弄一个上传文件类型用户组 (#141)




 
这是图床，图片类型也就那么多，为什么还要设置不同图片类型的用户组？

**Comment by xiaoyi688** [comment]
还有那个，希望可以加上友链功能，那个图片鉴黄接口貌似申请不了，申请提示错误，不知道啥原因



---原始邮件---
发件人: "Wisp X"<notifications@github.com&gt;
发送时间: 2020年7月9日(周四) 下午4:08
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "xiaoyi688"<2531170283@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] 希望可以弄一个上传文件类型用户组 (#141)




 
这是图床，图片类型也就那么多，为什么还要设置不同图片类型的用户组？

**Comment by renbaoshuo** [comment]
友链？这不是博客系统啊。。。想要可以自己改

图片鉴黄要挂梯子的

**Comment by xiaoyi688** [comment]
梯子?懂了，Thanks



---原始邮件---
发件人: "任宝硕"<notifications@github.com&gt;
发送时间: 2020年7月10日(周五) 上午9:37
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "xiaoyi688"<2531170283@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] 希望可以弄一个上传文件类型用户组 (#141)




 
友链？这不是博客系统啊。。。想要可以自己改
 
图片鉴黄要挂梯子的

**Comment by xiaoyi688** [comment]
还是提示&nbsp; &nbsp;错误，无法确定你不是机器人



---原始邮件---
发件人: "任宝硕"<notifications@github.com&gt;
发送时间: 2020年7月10日(周五) 上午9:37
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "xiaoyi688"<2531170283@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] 希望可以弄一个上传文件类型用户组 (#141)




 
友链？这不是博客系统啊。。。想要可以自己改
 
图片鉴黄要挂梯子的

**Comment by xiaoyi688** [comment]
你看



---原始邮件---
发件人: "任宝硕"<notifications@github.com&gt;
发送时间: 2020年7月10日(周五) 上午9:37
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "xiaoyi688"<2531170283@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] 希望可以弄一个上传文件类型用户组 (#141)




 
友链？这不是博客系统啊。。。想要可以自己改
 
图片鉴黄要挂梯子的

**Comment by xiaoyi688** [comment]
[http://url.imgu.vip/2020/07/10/5526f2c254beb.jpg](url)

**Comment by renbaoshuo** [comment]
这边建议您使用电脑的呢，手机验证会有问题

~~不会吧不会吧不会吧居然有人用手机建站~~

**Comment by renbaoshuo** [comment]
@wisp-x 可以把这个issue关掉了吧
