### ISSUE TITLE
is it in english too?

### ISSUE THREAD

**Issue by petrk94** [wisp-x/lsky-pro#145]

**Comment by wisp-x** [comment]
Sorry, not english.

**Comment by petrk94** [comment]
Why not? 
There is a huge self hosting community, which is interested in photo organizer, but without english, its, restricted to chinese only, whats sad.
Take a look here and ask for feedback https://www.reddit.com/r/selfhosted/

**Comment by wisp-x** [comment]
> Why not?
> There is a huge self hosting community, which is interested in photo organizer, but without english, its, restricted to chinese only, whats sad.
> Take a look here and ask for feedback https://www.reddit.com/r/selfhosted/

When I started this program, I did not consider internationalization, and my English ability was very poor.😅

**Comment by petrk94** [comment]
Maybe you can ask in the reddit community for translation help, unfortunately I can not chinese, but the UI is nice and would be helpful to get more people onboard to make it international more known

**Comment by wisp-x** [comment]
Thanks, maybe I will consider joining English in the future, but not now.😁
