### ISSUE TITLE
生成的链接为http

### ISSUE THREAD

**Issue by D-Myself** [wisp-x/lsky-pro#146]
如图，我开启了全站https，上传和浏览我的图片时显示的却是http，之前的却是正常的
![2020-07-15 07-30-49 的屏幕截图](https://user-images.githubusercontent.com/62274834/87486363-bf36dc80-c66d-11ea-969f-4eb9252517eb.png)
![2020-07-15 07-30-35 的屏幕截图](https://user-images.githubusercontent.com/62274834/87486357-bcd48280-c66d-11ea-95bc-8c0d7a448ff9.png)

**Comment by wisp-x** [comment]
后台设置->储存策略->域名一栏中，域名开头填写https:// 即可

**Comment by chenyichuk** [comment]
必须在链接前加https





---原始邮件---
发件人: "D-Myself"<notifications@github.com&gt;
发送时间: 2020年7月15日(周三) 上午7:37
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [wisp-x/lsky-pro] 生成的链接为http (#146)




 
如图，我开启了全站https，上传和浏览我的图片时显示的却是http，之前的却是正常的

**Comment by D-Myself** [comment]
ok
