### ISSUE TITLE
好像删除账号，不能删除账号下的数据（图片）

### ISSUE THREAD

**Issue by jonleeworld** [wisp-x/lsky-pro#148]
好像删除账号，不能删除账号下的数据（图片）

**Comment by wisp-x** [comment]
自信一点，把好像去掉，删除某个用户是不会清除该用户图片数据的

**Comment by jonleeworld** [comment]
可以增加成可选的吗，有些用户注册了就上传一堆违法图片，一个一个清理有点麻烦

或者在“”“图片管理”里，可以批量删除某用户的图片，这样好像也行得通

**Comment by haig233** [comment]
> 自信一点，把好像去掉，删除某个用户是不会清除该用户图片数据的

能不能加个选项，把图片也给删了，最近正好有这个需求
