### ISSUE TITLE
Users->default_folder  这个错误是admin账户没有创建默认目录？

### ISSUE THREAD

**Issue by m2xs** [wisp-x/lsky-pro#15]
![image](https://user-images.githubusercontent.com/18651998/50589497-d82fd080-0ec1-11e9-8e40-4396bc2e2fb1.png)

**Comment by m2xs** [comment]
安装好了以后，admin登陆以后点击“设置”就会报错。

**Comment by m2xs** [comment]
普通用户注册之后也一样会报这个错误。

**Comment by wisp-x** [comment]
安装还是更新？下载的master分支吗？

**Comment by m2xs** [comment]
安装，是下载的master




| |
mei2sir
邮箱：mei2sir@163.com
|

Signature is customized by Netease Mail Master

在2019年01月02日 21:39，熊二哈 写道：

安装还是更新？下载的master分支吗？
