### ISSUE TITLE
发现一个bug：同一文件夹图片超60后点击重置数据图片显示数目出错

### ISSUE THREAD

**Issue by ShaoPak** [wisp-x/lsky-pro#151]
我有一个文件夹里有67张图片，当我点击“重置数据”按钮后文件夹便只显示7张了，程序默认直接预览图片数是60。

请问如何解决，在程序里的哪个文件可以修改直接预览图片数目，把这个改成很大能否解决

**Comment by wisp-x** [comment]
application/index/controller/User.php 文件第 21 行，参数 limit 就是每页显示数量

**Comment by ShaoPak** [comment]
> application/index/controller/User.php 文件第 21 行，参数 limit 就是每页显示数量

感谢大佬的回复，问题解决了/开心
