### ISSUE TITLE
大图片超时上传失败

### ISSUE THREAD

**Issue by ShaoPak** [wisp-x/lsky-pro#152]
图片大一点显示timeout超时，无法上传，存储用的是又拍云USS，报错如图：
![image](https://user-images.githubusercontent.com/62377236/88450426-67744e80-ce81-11ea-98fb-2bce8f494825.png)

**Comment by wisp-x** [comment]
网关超时导致，上传受服务器带宽和网络影响

**Comment by ShaoPak** [comment]
> 网关超时导致，上传受服务器带宽和网络影响

原来还受限于服务器啊，我原来以为主要是网络的问题，4G和100M宽带wifi试了都不行
