### ISSUE TITLE
图片复制链接可以支持https吗

### ISSUE THREAD

**Issue by shadowfish07** [wisp-x/lsky-pro#153]
我部署的图床本身和存储策略都是支持https的，但是API和直接网站里复制图片链接出来的网址都是http的，这样子如果直接用在其他网站上会报https部分不安全，希望支持一下https的图片地址导出

**Comment by wisp-x** [comment]
请仔细看文档：https://www.kancloud.cn/wispx/lsky-pro/1526363

**Comment by shadowfish07** [comment]
谢谢，解决了
