### ISSUE TITLE
设置管理员账号时配置文件写入失败

### ISSUE THREAD

**Issue by r3nzh3n9** [wisp-x/lsky-pro#155]
## 环境
- lsky-pro 版本：`V1.6.1`
- LNMP 版本： `lnmp.org lnmp1.7`
- 网站根目录:  `/home/wwwroot/domain.tld`

## 操作步骤
前提：按照要求开启 fileinfo 拓展，并且按照 #31 修改网站配置文件 `vhost/domain.tld.conf`
1. 切换至网站根目录并且下载源码

    ```
    wget https://github.com/wisp-x/lsky-pro/archive/v1.6.1.zip
    unzip v1.6.1.zip 
    ```
2.  整理目录

    ```
    rm -rf v1.6.1.zip && mv lsky-pro-1.6.1/* . && rm -rf lsky-pro-1.6.1/
    ```
3.  修改权限

    ```
    chown -R www:www .
    ```
4.  网站根目录 `/home/wwwroot/domain.tld` 如下：

    ![Snipaste_2020-07-26_18-10-45.png](https://i.loli.net/2020/07/26/zQKuOZsTnxEN6fH.png)

5. 访问 `domain.tld` 正常：
    
    ![Snipaste_2020-07-26_18-02-07.png](https://i.loli.net/2020/07/26/sbKVk6QcJNmahqZ.png)

## 出现问题

1. 按照提示进行数据库配置
    
   略

2. 按照要求配置管理员账号，点击 “设置管理员账号” 时出现 “配置文件写入失败” 报错。如下图所示：

    ![Snipaste_2020-07-26_17-58-35.png](https://i.loli.net/2020/07/26/UjNyZtXo86her7l.png)

**Comment by wisp-x** [comment]
检查程序根目录是否存在```.env.example```文件

**Comment by r3nzh3n9** [comment]
网站根目录下没有 `.env.example`；重新下载了一份 `v1.6.1.zip`，解压之后有 `.env.example` 。

目前已经安装成功。

十分感谢！
