### ISSUE TITLE
当两张图片内容不同而MD5相同时，上传会出错，只能上传其中一张

### ISSUE THREAD

**Issue by hapke24** [wisp-x/lsky-pro#156]
### 上传结果
![image](https://user-images.githubusercontent.com/49407099/88667493-07e1a180-d114-11ea-9297-819db798dcba.png)
### 测试图片
![ship](https://user-images.githubusercontent.com/49407099/88667758-61e26700-d114-11ea-96c6-518313973af8.jpg)

![planes](https://user-images.githubusercontent.com/49407099/88667787-66a71b00-d114-11ea-80ed-d47971e546da.jpg)
### 建议
- 使用两种及以上的哈希算法来确定图片是否相同

**Comment by wisp-x** [comment]
还有这种操作我是没想到的

**Comment by hapke24** [comment]
> 还有这种操作我是没想到的

百度网盘和知乎也没逃过

**Comment by lePig** [comment]
涨见识了， 确实得使用2种以上来判断。
使用sha1算出来就是不同的。

**Comment by Minscs** [comment]
文件: C:\Users\Admin\Desktop\1.jpg
大小: 335104 字节
修改时间: 2020年7月30日, 15:04:32
MD5: 253DD04E87492E4FC3471DE5E776BC3D
SHA1: 9639DB1FBADFCFBD4025A9B95D10B7799F65FCFB
CRC32: 690FC689

文件: C:\Users\Admin\Desktop\2.jpg
大小: 335104 字节
修改时间: 2020年7月30日, 15:04:59
MD5: 253DD04E87492E4FC3471DE5E776BC3D
SHA1: 780973C1C165E76DE3F10E1771DB31CF9362D1F5
CRC32: 7FD01BDA


这是啥原理，为啥MD5相同

**Comment by hapke24** [comment]
> 文件: C:\Users\Admin\Desktop\1.jpg
> 大小: 335104 字节
> 修改时间: 2020年7月30日, 15:04:32
> MD5: 253DD04E87492E4FC3471DE5E776BC3D
> SHA1: 9639DB1FBADFCFBD4025A9B95D10B7799F65FCFB
> CRC32: 690FC689
> 文件: C:\Users\Admin\Desktop\2.jpg
> 大小: 335104 字节
> 修改时间: 2020年7月30日, 15:04:59
> MD5: 253DD04E87492E4FC3471DE5E776BC3D
> SHA1: 780973C1C165E76DE3F10E1771DB31CF9362D1F5
> CRC32: 7FD01BDA
> 这是啥原理，为啥MD5相同

MD5是有穷的，数据是无穷的，加上MD5碰撞算法的出现，这两张图就出来了。
[末尾有相关论文链接](https://www.zhihu.com/answer/980544776)
