### ISSUE TITLE
请问怎么获取token

### ISSUE THREAD

**Issue by tcjlj** [wisp-x/lsky-pro#157]
请问怎么获取token

**Comment by wisp-x** [comment]
通过接口获取

**Comment by skybbx** [comment]
可以具体点吗？{"code":500,"msg":"账号不存在","data":{},"time":1596903091}

**Comment by xsfecho** [comment]
你POST邮箱+密码给接口就行
参数名称 | 类型 | 是否必须 | 说明
-- | -- | -- | --
email | String | 是 | 邮箱
password | String | 是 | 账号密码

**Comment by skybbx** [comment]
> 你POST邮箱+密码给接口就行
> 
> 参数名称	类型	是否必须	说明
> email	String	是	邮箱
> password	String	是	账号密码

感谢，已经解决了。
