### ISSUE TITLE
分用户设置存储路径（云存储和本地分开设置路径）

### ISSUE THREAD

**Issue by wsczx** [wisp-x/lsky-pro#162]
能否云存储和本地存储路径分开设置？而不是目前设置的默认目录？比如：我自己的账号是设置的默认上传到七牛云根目录，但是其他用户设置的存储为本地时，也同样上传到服务器的根目录了，这样会造成图片全在服务器的根目录很混乱，谢谢！！！

**Comment by wisp-x** [comment]
你给某用户分配了哪种策略则上传的图片就在该策略的储存下，同一种策略不能设置不同的用户的上传路径。

**Comment by wsczx** [comment]
我的意思是，不管云存储还是本地存储，上传配置里面的
![image](https://user-images.githubusercontent.com/31199914/90714884-47e31100-e2db-11ea-86a9-c1831a05460f.png)
上传路径设置都是共享的，因为云存储的图片都是在根目录，所以这个地方我留空了，但是如果是本地存储的用户上传也是使用这个配置，同样上传到服务器的根目录了，是这个问题
![image](https://user-images.githubusercontent.com/31199914/90714985-85479e80-e2db-11ea-952a-80efc5ec13f2.png)

**Comment by wisp-x** [comment]
设计如此，路径命名规则会应用所有策略，不支持单个策略独立设置
