### ISSUE TITLE
在我的图片栏目不能新建文件夹

### ISSUE THREAD

**Issue by zhaokelei** [wisp-x/lsky-pro#163]
在我的图片栏目不能新建文件夹
![image](https://user-images.githubusercontent.com/17022061/91419762-61113200-e886-11ea-84fe-832eaec31b1b.png)

**Comment by wisp-x** [comment]
右键即可，
![image](https://user-images.githubusercontent.com/22728201/91523708-03392480-e930-11ea-8e86-12f8c063cc64.png)
