### ISSUE TITLE
似乎上传同样的文件，返回的URL是第一次上传的，可以手动关闭这个特性吗？

### ISSUE THREAD

**Issue by shadowfish07** [wisp-x/lsky-pro#164]
因为业务需求，同样的文件多次上传需要每次都存储而且返回独一无二的URL

**Comment by wisp-x** [comment]
暂不支持关闭，需要修改代码，注释掉 Upload.php 文件中的第 108-111 行和第 121 行即可
https://github.com/wisp-x/lsky-pro/blob/master/application/common/controller/Upload.php#L108-L111

或者增加额外参数来修改上传后的 url，详见：https://www.kancloud.cn/wispx/lsky-pro/1569427 中的 ```system.url_query```

**Comment by shadowfish07** [comment]
好的，感谢，问题解决了
