### ISSUE TITLE
图片管理中出现好多空白占位空图

### ISSUE THREAD

**Issue by 1kuxyz** [wisp-x/lsky-pro#166]
我批量上传了20来张图，包含png、jpg、gif、jfif格式，但上传之前没有设置允许上传jfif格式的图片，虽然上传后提示了jfif格式的几张图失败了，但进如图片管理页面，发现多出多个空白占位，怎么才能去掉呢？
![image](https://user-images.githubusercontent.com/40167317/94559623-1c692400-0294-11eb-8953-5bbb179ef99c.png)

**Comment by wisp-x** [comment]
分辨率调整一下就好了，样式的问题

**Comment by 1kuxyz** [comment]
电脑的分辨率吗？还是浏览器的？还有我试了一下手机移动端，也是有空白占位
![photo_2020-09-30_21-28-20](https://user-images.githubusercontent.com/40167317/94691935-851fd180-0364-11eb-8d0e-9cbed340bfc4.jpg)
