### ISSUE TITLE
多图片上传，一键复制链接

### ISSUE THREAD

**Issue by xingline** [wisp-x/lsky-pro#167]
当多图上传时，目前需要一个一个链接去复制链接，很慢，建议加个一键下载，也就是一行一个图片url，.txt文件

**Comment by 1kuxyz** [comment]
我也想要这个功能。
我现在的解决办法是，当多图上传完成时，会在页面下会生成这次所有上传成功的图片连接，复制到txt里保存好，以后备用。
![image](https://user-images.githubusercontent.com/40167317/95010684-e47c2b00-065d-11eb-9bce-749954b950af.png)

**Comment by xingline** [comment]
你这个也基本可以实现需求了，不错谢谢分享，不过我一次上传50甚至更多的图片，一键复制或者下载文件就更好了
