### ISSUE TITLE
图片预览bug

### ISSUE THREAD

**Issue by Mr-Liu1996** [wisp-x/lsky-pro#171]
图片链接可以使用但是在个人中心里图片无法预览
![Screenshot_2020-11-14-09-36-34-05_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/58027529/99135392-f984aa80-265c-11eb-9769-795c0b22017a.jpg)

**Comment by wisp-x** [comment]
检查你的策略域名是否正确
