### ISSUE TITLE
请求修复后台IP接口失效的问题

### ISSUE THREAD

**Issue by waterrr** [wisp-x/lsky-pro#179]
众所周知，淘宝的IP接口很久之前挂了。
./application/index/controller/admin/Images.php #Line 136
原接口

>http://ip.taobao.com/service/getIpInfo.php?ip=114.114.114.114

更新后的接口
>http://ip.taobao.com/outGetIpInfo?ip=114.114.114.114&accessKey=alibaba-inc

好吧，才发现第一个加个accessKey也可以
>http://ip.taobao.com/service/getIpInfo.php?ip=114.114.114.114&accessKey=alibaba-inc

dalao别摸鱼啦，快来更新，等一个v1.6.2版本。

**Comment by wisp-x** [comment]
感谢反馈，我抽空处理一下
