### ISSUE TITLE
1.6.1版本上传图片无法显示问题

### ISSUE THREAD

**Issue by yuchong111** [wisp-x/lsky-pro#181]
之前用的是5.9版本，然后现在用的1.6.1版本上传图片以后访问图片地址不能正常显示，显示404 Not Found，服务器用的是nginx，伪静态也配置了，之前版本可以正常显示，请问这是什么问题。

**Comment by wisp-x** [comment]
如果是本地储存，检查本地文件是否存在，第三方储存检查域名是否正确

**Comment by yuchong111** [comment]
> 如果是本地储存，检查本地文件是否存在，第三方储存检查域名是否正确
用的第三方，域名都正确，图片可以存储到第三方储存，第三方储存也能看到图片，但是图片链接查看显示不了

**Comment by yuchong111** [comment]
> 如果是本地储存，检查本地文件是否存在，第三方储存检查域名是否正确

解决了，只能用全球加速，用中国境外不能正常显示
