### ISSUE TITLE
能否对接一下sm.ms

### ISSUE THREAD

**Issue by G3WCN** [wisp-x/lsky-pro#189]
能否对接一下sm.ms，新浪，葫芦侠，百度等图床，后台选择上传

**Comment by onjicn** [comment]
同求，有个案例即可，其他接口可以自己抓

**Comment by wisp-x** [comment]
实际上不难对接，实现 https://github.com/wisp-x/lsky-pro/blob/master/extend/strategy/Driver.php 接口即可，可以模仿一下其他的策略驱动
