### ISSUE TITLE
使用PHP8时，添加角色组导致错误

### ISSUE THREAD

**Issue by HazukiKaguya** [wisp-x/lsky-pro#199]
使用PHP8.0.3时，在【系统管理-角色组-https://url.url/admin/group/index.html 】页面添加角色组后，会导致【角色组】页面错误【系统发生错误-https://url.url/admin/group/index.html#mdui-dialog 】
如图：
![image](https://user-images.githubusercontent.com/35645329/115555634-ae955000-a2ea-11eb-9396-7776d5dd0076.png)

**Comment by J2zl** [comment]
可以吧debug打开看看

**Comment by Beattheend** [comment]
![就像这样](https://user-images.githubusercontent.com/64207250/124126082-e0762000-daac-11eb-801d-8e1ed57dd105.png)
