### ISSUE TITLE
作者大大水印位置是否考虑可以设置成随机

### ISSUE THREAD

**Issue by liub1934** [wisp-x/lsky-pro#203]
locate: 水印位置[1=左上角,2=上居中,3=右上角,4=左居中,5=居中,6=右居中,7=左下角,8=下居中,9=右下角]
locate能否考虑设置random，每张上传的图片随机以上的水印位置

**Comment by wisp-x** [comment]
试试这样：
```php
// ...
'locate' => rand(1, 9),
// ...

```
