### ISSUE TITLE
更新1.6.3版本后新上传的图片无法通过URL访问

### ISSUE THREAD

**Issue by acgbox233** [wisp-x/lsky-pro#204]
1.6.3版本：
上传新图片后，查到文件权限是600，通过URL链接无法查看图片，需要手动修改权限为755后才能访问。
也就是说每次上传新图片后都得手动提升文件权限才能通过URL查看图片。
![photo_2021-04-23_16-14-42](https://user-images.githubusercontent.com/40623378/115866581-7453bc00-a46c-11eb-92e2-5d76bd43fd30.jpg)

**Comment by wisp-x** [comment]
检查你的运行环境

**Comment by acgbox233** [comment]
PHP更换成7.4后依然是这个问题。文件权限755、用户组www、伪静态、PHP插件这些都是正确设置了的。
程序升级到1.6.3版本之前一切正常。

**Comment by acgbox233** [comment]
全新安装1.6.3版本也是这样，新上传的图片文件权限总是会被自动改成600
是不是因为面板的原因？我用的是AppNode而不是宝塔面板。

**Comment by pope-L** [comment]
我也是这样，  上传的图片600权限只能 apache用户/组访问
nginx是nginx 用户/组，php-fpm是apache用户/组
nginx1.14 php7.2.24 centos8
都是 yun install 的
如果访问不存在的图片  会显示 _页面错误！请稍后再试～_ 但 runtime下的log文件里没错误提示

**Comment by pope-L** [comment]
临时笨办法
/usr/share/nginx/html/extend/strategy/driver/Local.php
第64行 加 这么chmod($file,0666);一句
参考下面
    public function create($pathname, $file)
    {
        $path = $this->rootPath . dirname($pathname) . DIRECTORY_SEPARATOR;
        if (true === $this->checkPath($path)) {
		chmod($file,0666);

**Comment by acgbox233** [comment]
> 临时笨办法
> /usr/share/nginx/html/extend/strategy/driver/Local.php
> 第64行加了chmod（$ file，0666）;一句
> 参考下面
> public function create（$ pathname，$ file）
> {
> $ path = $ this-> rootPath。dirname（$路径名）DIRECTORY_SEPARATOR;
> 如果（true === $ this-> checkPath（$ path））{
> chmod（$ file，0666）;

确实可以用。

**Comment by ruyisi** [comment]
我用的是1.6.4版本。

里面的语法是这样的。
```
    /**
     * 创建本地文件
     *
     * @param $pathname 文件路径加文件名
     * @param $file     文件资源路径
     *
     * @return bool
     */
    public function create($pathname, $file)
    {
        $path = $this->rootPath . dirname($pathname) . DIRECTORY_SEPARATOR;
        if (true === $this->checkPath($path)) {
            if (rename($file, $pathname)) {
                _**chmod($file, 0666);**_
                return true;
            }
        }
        $this->error = '文件移动失败';

        return false;
    }
```
如果我直接加chmod($file,0666);。就会报错了。

**Comment by ruyisi** [comment]
经过邮件咨询，如果是1.6.4版本，用chmod($pathname, 0755);可以解决本问题。
