### ISSUE TITLE
不能打开 设置页面

### ISSUE THREAD

**Issue by pope-L** [wisp-x/lsky-pro#205]
centos8 nginx php
...
	index index.php;
    server {
        listen       80 default_server;
        root         /usr/share/nginx/html/public;
        location / {
		    if (!-e $request_filename) {
		    	rewrite ^(.*)$ /index.php?s=$1 last; break;
		    }
        }
...
压缩包是解压在html目录里
http://xx.xx/打开后跳转http://xx.xx/install/index.html 无设置界面 页面不存在

**Comment by wisp-x** [comment]
检查你的伪静态配置是否生效

**Comment by pope-L** [comment]
y原来是下面 这个没注释 但是注释后
#        error_page 404 /404.html;
#            location = /40x.html {
#        }

#        error_page 500 502 503 504 /50x.html;
#            location = /50x.html {
#        }
 但是注释后，页面正常显示出错信息了，
php-fpm的log中显示如下
_[24-Apr-2021 12:17:16 Asia/Shanghai] PHP Fatal error:  Uncaught think\exception\ErrorException: mkdir(): Permission denied in /usr/share/nginx/html/thinkphp/library/think/log/driver/File.php:61
Stack trace:
#0 [internal function]: think\Error::appError(2, 'mkdir(): Permis...', '/usr/share/ngin...', 61, Array)
#1 /usr/share/nginx/html/thinkphp/library/think/log/driver/File.php(61): mkdir('/usr/share/ngin...', 493, true)
#2 /usr/share/nginx/html/thinkphp/library/think/Log.php(224): think\log\driver\File->save(Array, true)
#3 /usr/share/nginx/html/thinkphp/library/think/Error.php(94): think\Log->save()
#4 [internal function]: think\Error::appShutdown()
#5 {main}
  thrown in /usr/share/nginx/html/thinkphp/library/think/log/driver/File.php on line 61_
会是 哪里权限不对？

**Comment by wisp-x** [comment]
检查你的 web 目录权限所有者是否为 www，还有 runtime 目录权限是否为 0755 或 0777

**Comment by pope-L** [comment]
`
![del2](https://user-images.githubusercontent.com/32924101/115947405-fe963180-a4f9-11eb-8e34-b002870a660a.PNG)
`
