### ISSUE TITLE
远程FTP上传，无法访问图片

### ISSUE THREAD

**Issue by LFMcxixif** [wisp-x/lsky-pro#207]
域名是否要和连接地址一样？
上传没问题，但是访问图片的时候不行。
![image](https://user-images.githubusercontent.com/69949204/116965566-b8528680-ace0-11eb-9d01-e7324da6d1a1.png)

**Comment by wisp-x** [comment]
![image](https://user-images.githubusercontent.com/22728201/117107805-c540aa00-adb4-11eb-871b-ff808e62e0cb.png)

**Comment by LFMcxixif** [comment]
留空也不行，咋个方法获得FTP里的文件

**Comment by xiaomutongxue** [comment]
请问这个解决了么，我也是正常上传，无法调用打开
