### ISSUE TITLE
如何修改让「系统管理」默认状态栏折叠起来

### ISSUE THREAD

**Issue by rzfyu** [wisp-x/lsky-pro#209]
个人使用，下面的功能万年不用一次，总是默认展开看着繁冗，希望它默认折叠，但是我不知道改哪里的代码，有人知道么指导一下。

**Comment by wisp-x** [comment]
https://github.com/wisp-x/lsky-pro/blob/4c789dd99a40bbb2c3e0ba2da80a57bf13d094c6/application/index/view/common/base.html#L84
去掉 ```mdui-collapse-item-open``` 即可

**Comment by ghost** [comment]
d
