### ISSUE TITLE
迁移后出错

### ISSUE THREAD

**Issue by ZC-TigerRoot** [wisp-x/lsky-pro#211]
![image](https://user-images.githubusercontent.com/66396101/118354664-b6b97600-b59e-11eb-8365-88ba19f1a75a.png)
[链接](https://image.tigerroot.cn/)

**Comment by wisp-x** [comment]
.env 文件中开启 debug
```
[app]
debug = true
```
可以显示详细的错误信息

**Comment by ZC-TigerRoot** [comment]
开启了，但是好像没区别……

**Comment by QinHongZhe** [comment]
删除application目录下install.lock

执行touch install.lock(重新新建即可解决)

我已经验证过，可以试试。

**Comment by ZC-TigerRoot** [comment]
![image](https://user-images.githubusercontent.com/66396101/118650089-a3184480-b816-11eb-8167-8b27b7933596.png)
新建后还是不行啊o(╥﹏╥)o

**Comment by SwordPal** [comment]
> ![image](https://user-images.githubusercontent.com/66396101/118650089-a3184480-b816-11eb-8167-8b27b7933596.png)
> 新建后还是不行啊o(╥﹏╥)o

别新建，删除之后刷新网页，就可以了，亲测

**Comment by akatsukiro** [comment]
删除该文件之后会重新安装，重新安装后原有数据无法使用，就变成一个新的兰空了啊，那么迁移的目的就丢失了啊。
