### ISSUE TITLE
图片鉴黄问题

### ISSUE THREAD

**Issue by bbs866** [wisp-x/lsky-pro#214]
开了图片鉴黄功能上传图片给了这个提示Could not retrieve the URL specified
怎么办求解

**Comment by bbs866** [comment]
是不是需要修改成post请求方式

**Comment by bbs866** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wisp-x/lsky-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月19日(星期三) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wisp-x/lsky-pro] 图片鉴黄问题 (#214)





 
可能是被墙了，鉴黄服务器无法获取到你的图片资源。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







您有什么解决办法吗

**Comment by wisp-x** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wisp-x/lsky-pro" ***@***.***&gt;; 发送时间:&nbsp;2021年5月19日(星期三) 下午3:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wisp-x/lsky-pro] 图片鉴黄问题 (#214) 可能是被墙了，鉴黄服务器无法获取到你的图片资源。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您有什么解决办法吗

换国外的服务器应该能解决，或者为你的图片资源加上全球cdn

**Comment by bbs866** [comment]
明白了谢谢您
