### ISSUE TITLE
发现一个奇葩问题，最新1.6.3上传文件权限为600

### ISSUE THREAD

**Issue by cdncomco** [wisp-x/lsky-pro#217]
1.6.1版本上传图片权限为644，1.6.3版本不管是全新安装还是升级 上传图片权限为600，导致用图片链接打开403

**Comment by acgbox233** [comment]
这个问题我之前反映过，但并没有引起开发者的重视。

**Comment by acgbox233** [comment]
https://github.com/wisp-x/lsky-pro/issues/204
有大佬给出了临时解决方法：
在图床程序的/extend/strategy/driver/Local.php的第64行增加一行代码`chmod($file,0755);`
参考下面：
> public function create($pathname, $file)
> {
> $path = $this->rootPath . dirname($pathname) . DIRECTORY_SEPARATOR;
> if (true === $this->checkPath($path)) {
> chmod($file,0755);
