### ISSUE TITLE
油猴脚本跨域登录信息获取问题

### ISSUE THREAD

**Issue by HazukiKaguya** [wisp-x/lsky-pro#219]
https://greasyfork.org/zh-CN/scripts/379924
按这个改了下用作自建图床的便捷上传脚本，但弹出的iframe内的兰空图床无法获取登录信息，目前只能游客上传，请问如何解决？

**Comment by wisp-x** [comment]
跨站 iframe 无法跟踪 cookie，但似乎是可以解决的，我也没研究过。
