### ISSUE TITLE
请问为什么我上传以后直接打开文件是没问题的，但在图片管理里面却打不开？

### ISSUE THREAD

**Issue by ddkk3000** [wisp-x/lsky-pro#22]
是不是传到我自己服务器上了？这很没必要，而且自己的服务器访问速度也不够。简单的说，我希望直接提供存储地（如七牛）的链接，而不是程序所在服务器的。

例如，我上传完毕以后显示下面的信息：

![mark](http://cache.lixiaozhe.com/image/20190204/ykKgOhNV0vML.png?imageslim)

里面的地址（“http://photo.lixiaozhe.com/2019/02/04/5c572beaee917.jpg”）确实可以访问

但是，我在图片管理中，这个地址是不能访问的，如图：

![mark](http://cache.lixiaozhe.com/image/20190204/JQMrKyFNO0oj.png?imageslim)

图中地址：http://cache.lixiaozhe.com/2019/02/04/5c572beaee917.jpg

另外，我传有些图居然还有大小限制，请问在哪里解除？

![mark](http://cache.lixiaozhe.com/image/20190204/veRMrJVafbhi.png?imageslim)

太魔性了，还有大小限制。

**Comment by ddkk3000** [comment]
我的截图不太好。我其实放开了文件打消限制。

![mark](http://cache.lixiaozhe.com/image/20190204/IbwSBxrfM2bs.png?imageslim)

**Comment by ddkk3000** [comment]
ps. cache.lixiaozhe.com 是七牛云，我在用户设置里已启用上传到七牛云。另外，我现在传图片突然这样了：

![mark](http://cache.lixiaozhe.com/image/20190204/fRCoJ6SffLbC.png?imageslim)

或者这样

![mark](http://cache.lixiaozhe.com/image/20190204/8eQpp4Hyak9D.png?imageslim)

不理解啊，既然传不了，程序进度条在跑什么呢？

**Comment by wisp-x** [comment]
你的PHP限制了文件上传size，更改限制请Google：upload_max_filesize
其他的可能是bug，抽空我看一下

**Comment by ddkk3000** [comment]
好的，感谢。那么怎么改好了该怎么长传呢？之前没有人用第三方图传，都是用本地的吗？



 
发件人： 熊二哈
发送时间： 2019-02-08 17:56
收件人： wisp-x/lsky-pro
抄送： ddkk3000; Author
主题： Re: [wisp-x/lsky-pro] 请问为什么我上传以后直接打开文件是没问题的，但在图片管理里面却打不开？ (#22)
你的PHP限制了文件上传size，更改限制请Google：upload_max_filesize
其他的可能是bug，抽空我看一下

**Comment by wisp-x** [comment]
@ddkk3000 同样的方式上传，到时候更新版本即可

**Comment by ddkk3000** [comment]
好的，感谢

获取 Outlook for Android

________________________________

**Comment by wisp-x** [comment]
@ddkk3000 测试发现没有问题，请检查你的七牛云配置是否正确，第一个加速域名不填就会默认使用当前站点域名。

**Comment by ddkk3000** [comment]
我又看了许多遍，我填写的信息是对的呀。

下面的图片是我现在用的上传图片程序（mpic）和文字处理软件软件（markeditor）所填写的信息（我用它们来说明自己填写正确）:

![mark](http://cache.lixiaozhe.com/image/20190208/SvgYOfmIVbtO.png?imageslim)
![mark](http://cache.lixiaozhe.com/image/20190208/8oxTP810DPSq.png?imageslim)

下面的图片是我lsky中的配置信息:

![mark](http://cache.lixiaozhe.com/image/20190208/UNAqgGayb0yJ.png?imageslim)

不用怀疑我前几个字符填写错误。

________________________________

发件人： 熊二哈<mailto:notifications@github.com>
发送时间： 2019-02-08 18:37
收件人： wisp-x/lsky-pro<mailto:lsky-pro@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [wisp-x/lsky-pro] 请问为什么我上传以后直接打开文件是没问题的，但在图片管理里面却打不开？ (#22)

@ddkk3000<https://github.com/ddkk3000> 测试发现没有问题，请检查你的七牛云配置是否正确，第一个加速域名不填就会默认使用当前站点域名。

**Comment by wisp-x** [comment]
@ddkk3000 储存策略里的CDN加速域名指的是七牛云的对象储存所绑定的加速域名

**Comment by ddkk3000** [comment]
啥意思？和其他软件不同在哪里？
________________________________

**Comment by wisp-x** [comment]
@ddkk3000 https://www.kancloud.cn/wispx/lsky-pro/880052

**Comment by ddkk3000** [comment]
我看了一下，没发现自己操作有问题。能简单说说我哪里做错了吗？感谢。
________________________________

**Comment by wisp-x** [comment]
@ddkk3000 看一下你当前用户所在的角色组所用的策略是否是七牛云，是的话应该是没有问题的

**Comment by ddkk3000** [comment]
不好意思，解决了，我选了“腾讯云”，可能是眼瞎了。

________________________________

发件人： 熊二哈<mailto:notifications@github.com>
发送时间： 2019-02-08 22:02
收件人： wisp-x/lsky-pro<mailto:lsky-pro@noreply.github.com>
抄送： ddkk3000<mailto:lixiaozhe@live.com>; Mention<mailto:mention@noreply.github.com>
主题： Re: [wisp-x/lsky-pro] 请问为什么我上传以后直接打开文件是没问题的，但在图片管理里面却打不开？ (#22)

@ddkk3000<https://github.com/ddkk3000> 看一下你当前用户所在的角色组所用的策略是否是七牛云，是的话应该是没有问题的
