### ISSUE TITLE
采用Webuploader插件上传对接API出错

### ISSUE THREAD

**Issue by doufuguolyl** [wisp-x/lsky-pro#223]
错误出现在上传完成返回信息部分，服务器返回错误提示“图片资源获取失败”

查看了一下调试信息，问题发生在 getImage() 函数，代码强制要求上传文件name为image类型，而使用百度webupload上传的图片的name都是file，所以就对代码稍微修改了一下，问题解决。

如果不影响整体代码逻辑的话，希望可以提交到下一版本中

`$image = $this->request->file('image');`
`if (null === $image) { // 这里是改进部分`
`    $image = $this->request->file('file');`
`}`
`if (null === $image) {`
`    throw new Exception('图片资源获取失败');`
`}`

**Comment by wisp-x** [comment]
建议在前端修改该名称。
![image](https://user-images.githubusercontent.com/22728201/121297473-ed2bac00-c924-11eb-8398-639acdc82904.png)
http://fex.baidu.com/webuploader/doc/index.html#WebUploader_Uploader_options

**Comment by doufuguolyl** [comment]
敢谢解答
