### ISSUE TITLE
您已超出本月免费请求的限制 (10000)。请访问mediumcontent.com 注册一个即用即付帐户。

### ISSUE THREAD

**Issue by jing5460** [wisp-x/lsky-pro#224]
![image](https://user-images.githubusercontent.com/38358681/122622312-de828900-d0ca-11eb-9ce0-c6adbc435ea3.png)

請問如何解決此問題

**Comment by penndu** [comment]
可以申请付费用户，没有数量限制，每1000张6块钱左右。
