### ISSUE TITLE
鉴黄不起作用

### ISSUE THREAD

**Issue by moeik** [wisp-x/lsky-pro#229]
已经申请key并且完成配置，不过尝试上传*图依旧能够正常上传，不会给出任何提示，但是后台已经标记可疑，并且在`图片管理`里面找不到，在`我的图片`里面能够找到，请问怎么解决？PS：图床放在国外 手动在官网Try it out没有问题能够鉴别

**Comment by wisp-x** [comment]
尝试将内容评级选项改为【成人】在重试一下。
此选项在下个版本会改为`非常严格`、`严格`、`一般`，对应现在的`所有人`、`少年`、`成人`

**Comment by moeik** [comment]
抱歉还是不起作用，我在.env里面将intercept_salacity = true，前端直接提示Url not accessible or malformed image, 是被墙的原因？我在官网输入图片链接能鉴别成功

**Comment by moeik** [comment]
将intercept_salacity = true 图片链接后面自动加上1类似.png1这样 所有出现提示Url not accessible or malformed image

**Comment by wisp-x** [comment]
大概率是被墙了，鉴黄服务器无法访问到该图片

**Comment by moeik** [comment]
作者你好，实测application/common/controller/Upload.php  177 lines判断有问题，将其改为：
```
//if (Config::get('system.intercept_salacity')) {
      $this->strategy->delete($pathname);
      throw new Exception('图片[' . $image->getInfo('name') . ']涉嫌违规，禁止上传！');
  //}
```
后 正常鉴别 望知悉
