### ISSUE TITLE
配置文件写入失败

### ISSUE THREAD

**Issue by longer008** [wisp-x/lsky-pro#230]
![image](https://user-images.githubusercontent.com/37037470/124412832-f708c980-dd81-11eb-99cc-19434740456c.png)
配置文件写入失败

**Comment by longer008** [comment]
上面这个问题的版本为最新版。换成1.54版本一切正常，等我过会儿升级最新版看看还有没有这个问题。

**Comment by xinchilde** [comment]
> 上面这个问题的版本为最新版。换成1.54版本一切正常，等我过会儿升级最新版看看还有没有这个问题。

老哥 1.6.3修复这个问题了么？ 1.54太老了吧

**Comment by longer008** [comment]
解决了，复制一份`.env.example`到项目根目录即可。
参考：
https://github.com/wisp-x/lsky-pro/issues/155#issue-665753259
https://github.com/wisp-x/lsky-pro/issues/125#issue-618051450

**Comment by longer008** [comment]
> > 上面这个问题的版本为最新版。换成1.54版本一切正常，等我过会儿升级最新版看看还有没有这个问题。
> 
> 老哥 1.6.3修复这个问题了么？ 1.54太老了吧

已解决
