### ISSUE TITLE
我的图片界面预览问题

### ISSUE THREAD

**Issue by akatsukiro** [wisp-x/lsky-pro#238]
~~没看到其他人有提出，可能是我自己的BUG？~~
如图所示 ![minebug](https://z3.ax1x.com/2021/07/17/W1rFw6.png)
窗口化后手动拖动至不同宽度，有正常的从左至右一一排列的，也有不正常排列如上图的。
浏览器：edge，91.0.864.70
我也不知道啥原因，所以只好麻烦作者大大了！

**Comment by wisp-x** [comment]
测试过似乎是长图导致的问题，有空再看看怎么解决。

**Comment by wisp-x** [comment]
Duplicate of #166
