### ISSUE TITLE
你好，能否添加一个上传至远程ftp服务器的功能呢

### ISSUE THREAD

**Issue by PYniang** [wisp-x/lsky-pro#24]
我有一台专门做存储的服务器，想在另外一台服务器上传图片直接到存储服务器，看里面只有一些第三方存储提供，请问能否添加这个功能呢

**Comment by wisp-x** [comment]
可以，有编程基础的可以尝试自己拓展一个第三方储存。  
储存驱动所在目录：```extend/strategy```  
储存驱动配置文件：```config/strategy.php```
配置数据表可参考其他储存驱动

**Comment by billy74** [comment]
我也有这个需求，自己找到了存储的驱动位置，但是不会编写FTP上传。。。
使用中还有一个问题就是切换到本地存储方式之后，上传回出现这个错误
http://file.mzfree.top/img/360chrome_lr4e3FpDqK.png
分析了一下 应该是文件移到的路径不对，并不是权限问题，因为它可以在public中创建以日期命名的文件夹，权限是有的，只是移动文件的时候，从临时文件夹移动到public的时候，临时文件夹路径错了，苦于不会调试，还请指点一二。
期待FTP方式上传

**Comment by wisp-x** [comment]
1.5.5已经支持[V1.5.5](https://github.com/wisp-x/lsky-pro/releases/tag/v1.5.5)

**Comment by cangshu2077** [comment]
你好，请问用远程服务器上传大于1M的就会失败，小的就没问题，这是什么情况啊
