### ISSUE TITLE
设置邮件出现问题

### ISSUE THREAD

**Issue by Plaudern** [wisp-x/lsky-pro#241]
在设置好邮件后进行测试，提示`mailer Error: SMTP connect() failed. `.

PHP版本7.3 已安装imap扩展

**Comment by penndu** [comment]
如果使用阿里云等主机，需要申请开启25端口才可以。

**Comment by Plaudern** [comment]
> 如果使用阿里云等主机，需要申请开启25端口才可以。

我的服务器不是阿里云腾讯云之类的，是个小厂，美国的服务器，宝塔的邮局可以正常收发邮件，因此25端口我可以确定是开放的。

**Comment by penndu** [comment]
1：php环境没有开启扩展php_openssl和php_sockets
2：协议或者端口错了，协议ssl和tls切换试试，端口25 587
 3：没有开启IMAP/SMTP服务（去邮箱设置开启）
