### ISSUE TITLE
能否支持github + jsdelivr

### ISSUE THREAD

**Issue by lbr77** [wisp-x/lsky-pro#244]
RT
应该是有api支持的
https://github.com/KnpLabs/php-github-api
然后可以转成jsdelivr链接
https://www.jsdelivr.com/github

**Comment by AH-dark** [comment]
这违背了jsDelivr的规则

https://github.com/jsdelivr/jsdelivr/blob/master/Acceptable%20Use%20Policy%20-%20jsdelivr.net.md#4-prohibited-use
