### ISSUE TITLE
smtp bug

### ISSUE THREAD

**Issue by 8838** [wisp-x/lsky-pro#247]
v1.6.3
测试smtp正常
找回密码无响应啊。未显示发送成功。更没有收到邮件。Gmail465

**Comment by wisp-x** [comment]
是bug，临时解决方案：
修改 `application/http/middleware/WebAuthenticate.php` 第 16 行，追加`'auth/sendCode'`
https://github.com/wisp-x/lsky-pro/blob/e7a08e59320fa85151c52b5044cbe0c88a9afb70/application/http/middleware/WebAuthenticate.php#L16-L26

**Comment by 8838** [comment]
改了之后可以收到邮件。不过收到的是个验证码。
上哪填。我是懵了
