### ISSUE TITLE
访问图片链接显示404

### ISSUE THREAD

**Issue by amggmm** [wisp-x/lsky-pro#251]
用的是腾讯云，然后我也在腾讯云看见了我上传的图片，但是访问图片的链接的时候显示404
用的是宝塔，PHP7.3，设置了伪静态

**Comment by amggmm** [comment]
用了腾讯云COS

**Comment by wisp-x** [comment]
检查 bucket 是否公开、域名是否正常解析、链接是否正确、以及防盗链规则。
