### ISSUE TITLE
容量无法修改

### ISSUE THREAD

**Issue by 3026187875** [wisp-x/lsky-pro#259]
**选项**
* [x] 是否有阅读文档？有
* [ ] Github issues 中是否存在相关问题？无
* [ ] 有没有尝试打开调试模式定位错误?不会

**描述问题**
对 bug 清晰而简洁的描述。

**错误信息**
如果出现错误提示，请打开调试模式(`.env`文件中的`debug`改为true)贴出详细的错误信息。
管理员账号修改容量不起作用？？初始容量只有1G太小了。怎么修改才能生效?
希望安装时可以自定义容量大小

**Comment by wisp-x** [comment]
系统设置中可以配置注册初始容量，也可以在用户管理中单独修改某个用户的容量。
