### ISSUE TITLE
ftp问题

### ISSUE THREAD

**Issue by a775566233** [wisp-x/lsky-pro#262]
**选项**
* [ 是] 是否有阅读文档？
* [ 否] Github issues 中是否存在相关问题？
* [ 是] 有没有尝试打开调试模式定位错误?

**描述问题**
系统：centos7
安装了宝塔并使用了内网穿透
使用了php7.4、nginx
下面是问题
默认使用了远程，也就是ftp。ftp内网主动和被动都可连接，上传图片后能正常发送到ftp服务器，ftp服务器内可查看图片，但是画廊那里看不到图，但能正常显示图片是什么时候上传的，存储策略的域名没填。
之后我使用了内网穿透后的ftp地址，filazilla的ftp客户端可以使用主动模式访问，可以正常上传和下载图片，但是图床不行。当地址
为ftp://域名 时，上传直接Remote：文件夹创建失败!，直接填地址，就一直处理中，然后ftp多了一些0B的文件，过了好久直接502 Bad Gateway，画廊哪里也没有显示图片
我并不清楚ftp拓展是否安装，但是图床的确是在内网情况下把图片上传到了ftp服务器上
**错误信息**
502 Bad Gateway
Remote：文件夹创建失败!

**Comment by wisp-x** [comment]
画廊中只会展示游客上传的图片。
ftp 的问题有待考究

**Comment by a775566233** [comment]
> 
> 
> 画廊中只会展示游客上传的图片。
> ftp 的问题有待考究

主要是我不知道那个域名该填什么，填ftp服务器？如果直接填ftp服务器域名，恐怕是打不开文件的吧。文档写得有点不详细
还有应该弄个打开图片后提供个图片外链代码什么的，而不是只给个图片连接。如果只在上传后才提供外链代码，会很不方便。
如果可以的话，弄个注册用户的画廊或者私密文件库，也是不错的
