### ISSUE TITLE
腾讯云cos问题

### ISSUE THREAD

**Issue by zrmugua** [wisp-x/lsky-pro#264]
cos存储能否通过服务器中转，走图床的域名，我怕被刷流量，反正内网流量是免费的

**Comment by wisp-x** [comment]
第三方储存图片上传流程：本地->服务器->第三方储存

**Comment by zrmugua** [comment]
@wisp-x 那能否通过服务器中转cos文件而不是直接走cos的链接呢

**Comment by Burial0268** [comment]
@zrmugua 那这样要cos有什么用呢，你搁着套娃呢（

**Comment by wisp-x** [comment]
> @wisp-x 那能否通过服务器中转cos文件而不是直接走cos的链接呢

理论上如果你的服务器和第三方储存的宽带在是同一地域，服务器->第三方储存这一步骤走的会是内网流量。

**Comment by Burial0268** [comment]
> > @wisp-x 那能否通过服务器中转cos文件而不是直接走cos的链接呢
> 
> 理论上如果你的服务器和第三方储存的宽带在是同一地域，服务器->第三方储存这一步骤走的会是内网流量。

要同一个服务商的云服务器才行吧
