### ISSUE TITLE
关于wordpress中无法使用External Media without Import插件导入图片到存储库

### ISSUE THREAD

**Issue by dreamstation625** [wisp-x/lsky-pro#265]
**选项**  
* [√] 是否有阅读文档？
* [×] Github issues 中是否存在相关问题？
* [×] 有没有尝试打开调试模式定位错误?

**描述问题**  
wordpress使用External Media without Import插件导入图片时，导入不成功，提示Failed to get info of the image(s). Please fill in the following properties manually. If you leave the fields blank (or 0 for width/height), the plugin will try to resolve them automatically. 但是文章内可以使用url显示图片，就是无法通过url导入图片到存储库中

**Comment by wisp-x** [comment]
不太清楚，可能和你的图片储存的服务器有关。

**Comment by dreamstation625** [comment]
好的好的，我再慢慢研究下，谢谢
