### ISSUE TITLE
页脚版权归属询问

### ISSUE THREAD

**Issue by Burial0268** [wisp-x/lsky-pro#271]
请问，页脚的[版权归属](https://gbcl.imgcdn.zyglq.cn/2021/11/07/ac4ed81dafddf.PNG)能不能更改，如果可以，请问在哪里可以修改呢？

**Comment by wisp-x** [comment]
/application/index/view/common/base.html 文件中修改

**Comment by Burial0268** [comment]
谢谢！！

**Comment by Burial0268** [comment]
Thanks!!!
