### ISSUE TITLE
【上传失败】Call to undefined function think\finfo_open()

### ISSUE THREAD

**Issue by SomUrim** [wisp-x/lsky-pro#273]
**选项**  
* [√] 是否有阅读文档？
* [×] Github issues 中是否存在相关问题？
* [√] 有没有尝试打开调试模式定位错误?

**描述问题**  

上传文件失败，包括对象储存及本地。

**错误信息**  

`Fatal error: Call to undefined function think\finfo_open() in /www/wwwroot/xxxxxxxxx/thinkphp/library/think/File.php on line 175`

POST Data
`image：{ "name": "QQ\u622a\u56fe20211115141433.png", "type": "image\/png", "tmp_name": "\/tmp\/phpPoNH0V", "error": 0, "size": 182137 }`

**其他信息**
- 软件版本：v1.6.3
- 运行环境：nginx/1.18.0
- PHP版本：5.6.40
- runtime、public目录权限：755（尝试过777）
- 文件名：QQ截图20211115141433.png
- 大小：177 KB
- 分辨率：1902*966

**Comment by wisp-x** [comment]
请安装 PHP 的 `fileinfo` 拓展

**Comment by SomUrim** [comment]
我可以了，谢谢

**Comment by wisp-x** [comment]
Duplicate #261
