### ISSUE TITLE
页面样式失效

### ISSUE THREAD

**Issue by 3232731490** [wisp-x/lsky-pro#282]
**描述问题**  
页面样式突然失效了

**错误信息**  
如果出现错误提示，请打开调试模式(`.env`文件中的`debug`改为true)贴出详细的错误信息。
错误信息如下：
GET https://cdn.jsdelivr.net/npm/viewerjs@1.5.0/dist/viewer.min.css net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/css/mdui.min.css net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/mdui@0.4.3/dist/js/mdui.min.js net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/marked@0.8.0/marked.min.js net::ERR_CERT_COMMON_NAME_INVALID
GET https://cdn.jsdelivr.net/npm/viewerjs@1.5.0/dist/viewer.min.js net::ERR_CERT_COMMON_NAME_INVALID

**Comment by wisp-x** [comment]
jsdelivr 炸了，走科学上网可以解决，或在项目目录搜索这些出错的链接，然后进行替换
https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.5.0/viewer.min.css
https://cdnjs.cloudflare.com/ajax/libs/mdui/0.4.3/css/mdui.min.css
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/mdui/0.4.3/js/mdui.min.js
https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js
https://cdnjs.cloudflare.com/ajax/libs/marked/0.8.0/marked.min.js
https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.5.0/viewer.min.js
