### ISSUE TITLE
可选关闭注册验证码

### ISSUE THREAD

**Issue by z0z0r4** [wisp-x/lsky-pro#289]
我试了七次，自己都看不出那是啥，破防了！
![image](https://user-images.githubusercontent.com/78744121/148670870-69efcfce-b84e-4942-83e5-3d0c1ed53635.png)
太难了这验证码........
![image](https://user-images.githubusercontent.com/78744121/148670880-e36e92ba-ec1c-4656-8fc6-3008ab2f0976.png)

**Comment by z0z0r4** [comment]
另外可否加一个用户流量上限？（害怕oss被刷爆...卖房很悲伤的
尤其是图床需要阿里key的情况下...要停下来只能删库

**Comment by wisp-x** [comment]
验证码你点一下不就换了吗...你的 oss 流量被刷图床也控制不了，上传之后给的图片都是直链，不经过图床程序。

**Comment by z0z0r4** [comment]
emmmm，我是换了七个图....

**Comment by z0z0r4** [comment]
另外，oss需要公共读吗？

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/148672590-7fe0bd32-6a60-4852-a22f-8a8a5627a091.png)
