### ISSUE TITLE
您好，是否考虑增加同时上传至多个云存储的功能？

### ISSUE THREAD

**Issue by SayaBear** [wisp-x/lsky-pro#29]
您好，现在配置用户组的时候需要遵循的规则是 注册用户-指定用户组-指定平台 ，上传时只能上传至某一个固定的云存储，因此是否考虑增加同时上传至多个云存储/图床的功能？

**Comment by wisp-x** [comment]
做分发吗？这样的话多图上传列表可能会混乱

**Comment by SayaBear** [comment]
对，本质就是分发，这样上传可以保证至少有一个备份站，一旦出现意外情况还可以恢复，对于对图片链接的保证性要求比较高的用户来说可能比较需要这个功能，不知道后台开发是否存在困难？

**Comment by wisp-x** [comment]
@SayaBear 可能需要到后期在考虑
