### ISSUE TITLE
oss策略下图片管理展示时能可选使用缩略图吗？

### ISSUE THREAD

**Issue by z0z0r4** [wisp-x/lsky-pro#291]
如图...这未免太耗流量了...图片管理界面下载的都是原图
或许可以在上传到oss后，本地弄一份缩略图上去？
选项总比无好
![image](https://user-images.githubusercontent.com/78744121/148673405-bed5d8fa-2d34-4004-90b4-6da721dfc5ba.png)

**Comment by wisp-x** [comment]
使用的是第三方储存那可以试试第三方的图片处理规则功能，不过需要修改代码。
https://github.com/wisp-x/lsky-pro/blob/e158be2ce265ff09049b7ac0678b7e4d078a601a/application/index/view/user/images.html#L175

假设你的处理规则定义的是类似这样的 
> http://domain.com/123456.jpg!preview

那么可以修改成
```
'        <img data-original="' + images[i].url + '" src="' + images[i].url + '!preview">' + 
```
