### ISSUE TITLE
上传图片后报错code32

### ISSUE THREAD

**Issue by GuuGuai** [wisp-x/lsky-pro#306]
windows server 2012R2
宝塔windows面板
php7.1
mysql5.5.62
nginx1.21.1
报错如下
rename(C:\Temp\php53A8.tmp,2022-02-21/2022-02-21.jpg): ��һ���������ʹ�ô��ļ��������޷����ʡ� (code: 32)

**Comment by wisp-x** [comment]
看起来应该是没有权限重命名。

**Comment by GuuGuai** [comment]
> 看起来应该是没有权限重命名。

有什么解决办法吗

**Comment by wisp-x** [comment]
https://github.com/wisp-x/lsky-pro/blob/e158be2ce265ff09049b7ac0678b7e4d078a601a/extend/strategy/driver/Local.php#L64
把这一行的 rename 改成 copy 试一下。

**Comment by GuuGuai** [comment]
> https://github.com/wisp-x/lsky-pro/blob/e158be2ce265ff09049b7ac0678b7e4d078a601a/extend/strategy/driver/Local.php#L64
> 
> 
> 把这一行的 rename 改成 copy 试一下。
可以了，感谢
