### ISSUE TITLE
上传文件经常失败

### ISSUE THREAD

**Issue by acgbox233** [wisp-x/lsky-pro#35]
上传文件稍微多一点点（10张+），就会容易出现上传失败的提示。
所以希望开发者能够将每次上传图片的机制更改为：执行上传操作时，系统分批次上传图片，而不是点击上传之后就全部统统上传。
![TC3J7A3SZ__CRQ__Q48K~UT.png](https://img.acgbox.top/2019/04/21/5cbc5740c4d09.png)

**Comment by imningfeng** [comment]
硬了

**Comment by muze-page** [comment]
上传时常常出现此类错误，希望能够改进。
