### ISSUE TITLE
能否考虑增加一个“提供能删除图片的链接”的功能呢？

### ISSUE THREAD

**Issue by Langlangagojoin** [wisp-x/lsky-pro#40]
Just like: ![SharedScreenshot.jpg](https://img.langlangago.xyz/2019/05/10/5cd59716db604.jpg)
图片显示不全，图片链接：https://img.langlangago.xyz/2019/05/10/5cd59716db604.jpg

**Comment by wisp-x** [comment]
考虑到已登录用户的原因，这块还没想好怎么处理。

**Comment by wisp-x** [comment]
1.5.5已经支持[V1.5.5](https://github.com/wisp-x/lsky-pro/releases/tag/v1.5.5)
