### ISSUE TITLE
使用宝塔面板windows版 出现无法上传图片问题 请求帮助

### ISSUE THREAD

**Issue by 5aihx** [wisp-x/lsky-pro#42]
我尝试了很多次 也配置了 临时文件夹和整个站点文件夹权限 但是不知道为什么无法上传 我到现在没找到原因
![sc](https://user-images.githubusercontent.com/42908276/57635409-a817dd00-75d9-11e9-92be-2b5935473217.jpg)
附网站环境截图
![hj](https://user-images.githubusercontent.com/42908276/57635567-fe851b80-75d9-11e9-976f-da1f73e2f6f2.jpg)
临时文件夹有临时文件 这我也懵了 就是不能上传 闹心
![fwq](https://user-images.githubusercontent.com/42908276/57635654-2b393300-75da-11e9-999c-02cee21ef677.png)
最后求作者大大帮忙 谢谢了

**Comment by wisp-x** [comment]
程序文件是放在c盘下安装的吗？如果是的话尝试换其他盘下安装。

**Comment by 5aihx** [comment]
网站不是在C盘  在D盘  目录也指定了  权限也给了  不知道哪里有问题

**Comment by 5aihx** [comment]
我换了IIS8.5环境 结果是这样
![Uploading bug.jpg…]()

**Comment by 5aihx** [comment]
我换了IIS8.5环境 结果是这样的
![bug](https://user-images.githubusercontent.com/42908276/57695139-0eefd180-7680-11e9-9345-8794b66f6171.jpg)

**Comment by wisp-x** [comment]
根目录新建 .env 文件，写入以下内容：
```
[APP]
debug = true
```
然后重新上传图片如果出错可以看到详细的错误信息，将错误信息截图贴出来看一下，涉及敏感信息可以直接发送到我的邮箱：i@wispx.cn
