### ISSUE TITLE
添加新功能：自定义图片名，根据图片名搜索，自定义OSS存储的“上传的目录”

### ISSUE THREAD

**Issue by muze-page** [wisp-x/lsky-pro#43]
我使用这个程序来管理我的在OSS的博客图片。
希望添加上述功能，方便图片的管理及日常的使用。

自定义选择在OSS中**上传的目录**

**Comment by wisp-x** [comment]
目前是可以根据文件名搜索，暂不支持重命名文件。
后台管理，设置里有文件夹、文件命名规则，自行修改即可。

**Comment by muze-page** [comment]
或者，就在本地，给图片弄个备注之类的，有时候，图片的名字，不一定能表达他的含义，在使用“唯一ID”的时候。

**Comment by muze-page** [comment]
自定义选择在OSS中**上传的目录**，见下图
![Snipaste_2019-05-17_11-57-01](https://user-images.githubusercontent.com/36845206/57902252-f4de0b00-789a-11e9-8d59-59839c4fbbc2.png)
文件路径命名规则(路径命名变量对照表)
img/{Y}/{m}/
