### ISSUE TITLE
运行速度慢

### ISSUE THREAD

**Issue by fcwys** [wisp-x/lsky-pro#47]
同一服务器下，打开这个图床总是慢一些，网站加了阿里云cdn，服务器2核4g，php7.3，运行tp的其他类型网站无此情况，望优化，谢谢！

**Comment by wisp-x** [comment]
图床的静态资源文件都是在本地的, 建议排查一下是否是其他原因导致的

**Comment by fcwys** [comment]
静态资源已缓存cdn，应该不会是静态资源加载的问题，且php开启了缓存插件
