### ISSUE TITLE
建议添加阿里云邮件推送

### ISSUE THREAD

**Issue by WhiteSnowPinkPinkWhatItLike** [wisp-x/lsky-pro#48]
如题，阿里云的好处很多：
* 每天免费 200 封，虽然自己的 163 QQ 没有限制，但是足够
* 成功率高
* 可以使用自己的域名，不用再给 163 什么的打广告，增加逼格

**Comment by billy74** [comment]
后台不是有smtp邮件设置了么。。。
你可以自己去配置一下参数，应该就可以了，还没用过邮件功能

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
阿里云似乎不能用 SMTP ？？
也许是我姿势不对。。。。

**Comment by WhiteSnowPinkPinkWhatItLike** [comment]
好吧，阿里云是可以使用 SMTP 的刚配置成功的。qwq
