### ISSUE TITLE
Windows IIS环境下,安装提示 ini_set(): A session is active. You cannot change the session module's ini settings at this time

### ISSUE THREAD

**Issue by WangWenBin2017** [wisp-x/lsky-pro#55]
Windows IIS 10.0,PHP7.3.3(FastCGI)无法安装,从第二步开始就提示:"ini_set(): A session is active. You cannot change the session module's ini settings at this time",不能继续。但是mysql表是正常创建的。求解

**Comment by wisp-x** [comment]
打开 ```config/session.php``` 文件，将 ```auto_start``` 的值改为 false
例：
```php
// 是否自动开启 SESSION
'auto_start' => false,
```

**Comment by WangWenBin2017** [comment]
修改了，还是一样的提示，重启机器也不行
