### ISSUE TITLE
开放注册之后，管理员在后台将用户删除之后，控制台还是显示的用户数量不会减少，并且数据库中lsky_users字段未删除

### ISSUE THREAD

**Issue by rangdengdashi** [wisp-x/lsky-pro#57]

**Comment by rangdengdashi** [comment]
手动将lsky_users的用户删除了之后，控制台的用户数量会减少

**Comment by rangdengdashi** [comment]
不好意思，没注意delete_time字段，但是用户删除了之后不能直接将用户的列删除了吗？

**Comment by wisp-x** [comment]
> 手动将lsky_users的用户删除了之后，控制台的用户数量会减少

这个是个 bug，后面会修复。


> 不好意思，没注意delete_time字段，但是用户删除了之后不能直接将用户的列删除了吗？

用户删除后不会真实删除，从数据库仍可以恢复，delete_time 就是删除时间。

**Comment by wisp-x** [comment]
已修复
