### ISSUE TITLE
图片排序问题

### ISSUE THREAD

**Issue by praming** [wisp-x/lsky-pro#59]
我是留作自用，所有图片都是在本地按序号重命名后上传至服务器，并且服务器文件名为原名，我发现批量上传后在我的图片里面排序是按着上传成功顺序排序，我希望按着文件名排序（顺序或倒序都可以），请问应该怎么做呢？

**Comment by wisp-x** [comment]
目前是按照你选择的图片顺序进行排序, 无法通过文件名进行排序.
