### ISSUE TITLE
程序严重安全缺陷反馈建议

### ISSUE THREAD

**Issue by kenser** [wisp-x/lsky-pro#6]
引用您的原话：
`默认程序的入口文件在 public 目录下，所以需要把public目录设置为网站运行目录，这样做是为了：
入口文件位置的设计是为了让应用部署更安全，public 目录为web可访问目录，其他的文件都可以放到非WEB访问目录下面。`

Warning: require(): open_basedir restriction in effect. File(/www/www_xxx_com/thinkphp/base.php) is not within the allowed path(s): 

然而在web服务器开启opendir设置后，该程序无法使用，因为不允许跨站。该程序的正常使用可能是建立在拱手把整个服务器权限开放给黑客的前提下的。建议把默认根目录换到public上级目录。

**Comment by wisp-x** [comment]
程序入口文件在public下面是框架推荐的方式，如非必要，不建议修改。
