### ISSUE TITLE
API上传经常出现timeout

### ISSUE THREAD

**Issue by weipeilong123** [wisp-x/lsky-pro#64]
我写的app上调用api上传图片，经常出现timeout，但是从后台可以看到图片已经上传成功了的

**Comment by wisp-x** [comment]
是服务端timeout了还是你写的请求timeout了？上传的图片过大响应时间就会慢，将请求的超时时间写大一点

**Comment by weipeilong123** [comment]
图片能够上传成功，但是接口返回timeout



---原始邮件---
发件人: "Wisp X"<notifications@github.com&gt;
发送时间: 2019年9月28日(星期六) 上午10:11
收件人: "wisp-x/lsky-pro"<lsky-pro@noreply.github.com&gt;;
抄送: "Perry_we"<wei917351143vip@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [wisp-x/lsky-pro] API上传经常出现timeout (#64)



是服务端timeout了还是你写的请求timeout了？上传的图片过大响应时间就会慢，将请求的超时时间写大一点
