### ISSUE TITLE
建议添加一个站内信功能，或者公告模块，有时候有的调整没办法及时通知用户

### ISSUE THREAD

**Issue by wclk** [wisp-x/lsky-pro#68]
站内信，公告，如果可以的也可以考虑商业版本，用户授权，激活码 内存 时间策略，最后希望新增一个可以查看指定用户的图片内容并且导出（因为有的用户想要后期导出到自己的服务器目前无法实现）
当然商业版本可以适当收费，力所能及会支持的！

**Comment by wclk** [comment]
而且我的图床目前后台 基础设置那里点了保存不会保存，必须要从数据库修改才会生效，不晓得咋子回事。

**Comment by wisp-x** [comment]
兰空图床会一直开源，不会考虑商业版本，实现整站通知可以自行修改模板来实现，模板路径在 ```application/index/view```

**Comment by wisp-x** [comment]
1.5.5已经支持[V1.5.5] (https://github.com/wisp-x/lsky-pro/releases/tag/v1.5.5)
