### ISSUE TITLE
Fatal error: Call to undefined function str_rand()

### ISSUE THREAD

**Issue by WangWenBin2017** [wisp-x/lsky-pro#71]
升级到1.5.5打开提示"Fatal error: Call to undefined function str_rand()"
网站:https://i.moeblog.top

**Comment by wisp-x** [comment]
检查一下你下载的版本，解压后文件是否完整。  
在检查一下  ```/application/common.php``` 文件里有没有 ```str_rand``` 函数。

**Comment by WangWenBin2017** [comment]
对了，因为我安装Lsky的是百度云虚拟主机，因此我按照教程修改了index.php，不知道是不是和这个有关。
common.php是在根目录下的，里面有一个str_rand函数。附common.php代码：
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: 流年 <liu21st@gmail.com>
// +----------------------------------------------------------------------

// 应用公共文件

/**
 * 转换文件大小单位
 *
 * @param $size
 * @param $array
 *
 * @return string|array
 */
function format_size($size, $array = false)
{
    if (0 == $size) {
        return "0.00 Bytes";
    }
    $unit = ['','K','M','G','T','P'];
    $base = 1024;
    $i = floor(log($size, $base));
    $n = count($unit);
    if($i >= $n) {
        $i = $n - 1;
    }

    if ($array) {
        return [sprintf("%.2f", $size / pow($base, $i)), $unit[$i] . 'B'];
    }

    return sprintf("%.2f", $size / pow($base, $i)) . ' ' . $unit[$i] . 'B';
}

/**
 * 格式化友好时间戳
 *
 * @param $unixTime
 * @return false|string
 */
function format_time($unixTime)
{
    $showTime = date('Y', $unixTime) . "年" . date('n', $unixTime) . "月" . date('j', $unixTime) . "日";
    if (date('Y', $unixTime) == date('Y')) {
        $showTime = date('n', $unixTime) . "月" . date('j', $unixTime) . "日 " . date('H:i', $unixTime);
        if (date('n.j', $unixTime) == date('n.j')) {
            $timeDifference = time() - $unixTime + 1;
            if ($timeDifference < 30) {
                return "刚刚";
            }
            if ($timeDifference >= 30 && $timeDifference < 60) {
                return $timeDifference . "秒前";
            }
            if ($timeDifference >= 60 && $timeDifference < 3600) {
                return floor($timeDifference / 60) . "分钟前";
            }
            return date('H:i', $unixTime);
        }
        if (date('n.j', ($unixTime + 86400)) == date('n.j')) {
            return "昨天 " . date('H:i', $unixTime);
        }
    }

    return $showTime;
}

/**
 * 过滤逗号(去除字符串两边的逗号，并将中文逗号转换成英文逗号)
 *
 * @param $str  字符串
 *
 * @return string
 */
function filter_comma($str)
{
    return trim(str_replace("，", ",", $str), ",");
}

/**
 * 获取文件后缀
 *
 * @param $name 文件名
 *
 * @return mixed
 */
function get_file_ext($name)
{
    return pathinfo($name, PATHINFO_EXTENSION);
}

/**
 * 随机字符串
 *
 * @param int $length
 * @param string $char
 * @return bool|string
 */
function str_rand($length = 16, $char = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ') {
    $string = '';
    for($i = $length; $i > 0; $i--) {
        $string .= $char[mt_rand(0, strlen($char) - 1)];
    }

    return $string;
}

/**
 * Make Token
 *
 * @return string
 */
function make_token()
{
    return md5('LSKY PRO' . uniqid() . time());
}

/**
 * Make Url
 *
 * @param $domain
 * @param null $pathname
 * @return mixed
 */
function make_url($domain, $pathname = null)
{
    $domain = rtrim($domain, '/');
    if (false === strpos($domain, 'https://') && false === strpos($domain, 'http://')) {
        $domain = 'http://' . $domain;
    }
    return str_replace('\\', '/', $domain . ($pathname ? '/' . $pathname : null));
}

/**
 * @param int $length
 * @return int
 */
function generate_code($length = 5) {
    $min = pow(10 , ($length - 1));
    $max = pow(10, $length) - 1;
    return rand($min, $max);
}

**Comment by WangWenBin2017** [comment]
抱歉，因为不是在我自己电脑上回复的，而用来回复的浏览器版本太低，github的代码格式化功能并不能正常使用。。。
我也按照教程把application文件夹内的内容全部剪切到根目录下了（百度虚拟主机貌似不支持运行目录功能）

**Comment by wisp-x** [comment]
> 而你如果安装时没有设置，使用 http://域名/public 的方式来访问站点，会导致 css 和 js 等静态资源无法获取。
如果你 无法 或 不会 设置运行目录，可以将 public 目录下的所有文件和文件夹（包括 .htaccess 文件）移动到根目录 (和 application 文件夹同级)即可，尽管我们不推荐你这么做，这样会导致应用程序核心文件暴露在外。  

确认你的操作是正确的，是把 ```public```目录的文件移动到根目录(和```application```同级)，教程没有说把```application```里面的文件夹剪切出来

**Comment by WangWenBin2017** [comment]
我错了我错了我错了，安装时把application当成public了。。。
