### ISSUE TITLE
上传竖立的照片自动变成横照

### ISSUE THREAD

**Issue by sunlewuyou** [wisp-x/lsky-pro#79]
![image](https://user-images.githubusercontent.com/19728435/73389340-ee9b9c00-430e-11ea-9ee1-9182be6a3d64.png)
不知何故，请您看看。谢谢！

**Comment by sunlewuyou** [comment]
是否上传时默认就会将所有照片根据宽高比把它统统转成横的了？那是否可以添加在后台能修改旋转图片的功能？谢谢！

**Comment by wisp-x** [comment]
上传图片并不会改变图片的方向
