### ISSUE TITLE
上传大小问题

### ISSUE THREAD

**Issue by xingline** [wisp-x/lsky-pro#81]
刚下载安装的新版本 发现2.7MB的gif提示 upload File size exceeds the maximum value

没有任何修改过
最大可上传 5 MB的图片，单次同时可选择 10 张。本站已托管 0 张图片。

**Comment by wisp-x** [comment]
检查你的 PHP 配置，最大上传值是否大于 2.7 M

**Comment by xingline** [comment]
还真是，打脸了嘿嘿
