### ISSUE TITLE
上传大文件(>50MB)报错

### ISSUE THREAD

**Issue by wutong233** [wisp-x/lsky-pro#89]
什么都不做的话上传会报错413 Request Entity Too Large
修改nginx配置为client_max_body_size 500m;后报错如下图
![image](https://user-images.githubusercontent.com/35332983/76199843-8e601a00-622b-11ea-9db4-49b7625e1d36.png)

**Comment by wisp-x** [comment]
根目录新建```.env```文件，内容：
```
[app]
debug = true
```

然后在试一下，截图看看详细错误信息，敏感信息记得要打码。

**Comment by wutong233** [comment]
> 根目录新建`.env`文件，内容：
> 
> ```
> [app]
> debug = true
> ```
> 
> 然后在试一下，截图看看详细错误信息，敏感信息记得要打码。

已创建并修改文件,如图
![image](https://user-images.githubusercontent.com/35332983/76207944-b22a5c80-6239-11ea-822b-d5aa72008d89.png),可并没有多出来什么信息,和以前一样

**Comment by wisp-x** [comment]
开启 debug 后会显示更多错误信息，其中包括了网站的 Session、Cookie、错误文件路径等，和以前一样的话请检查文件增加了是否已经生效。
