### ISSUE TITLE
开启图片鉴黄后，无法上传图片

### ISSUE THREAD

**Issue by kenser** [wisp-x/lsky-pro#9]
报错提示：
74.jpg: The request has timed out. Operation timed out after 15000 milliseconds with 0 bytes received.
如果上传的时候有问题，建议用户上传后显示可疑图片，由管理员决定是否删除

**Comment by wisp-x** [comment]
请求鉴黄接口超时了，你试一下在你的服务器上ping www.moderatecontent.com看看有没有问题
