### ISSUE TITLE
希望增加静态文件CDN加速的功能

### ISSUE THREAD

**Issue by renbaoshuo** [wisp-x/lsky-pro#90]
如题，小水管服务器真的很慢，可以在后台添加一个静态文件CDN加速的配置

**Comment by wisp-x** [comment]
下个版本添加。

**Comment by Yuii-guoguo** [comment]
> 如题，小水管服务器真的很慢，可以在后台添加一个静态文件CDN加速的配置

你服务器加载静态都卡吗？

**Comment by renbaoshuo** [comment]
> 你服务器加载静态都卡吗？

@Yuii-guoguo  1Mbps带宽，不知道为啥加载要个十几秒，自己搭了个CDN添加之后显示不正常
