### ISSUE TITLE
文件别名在哪设置？

### ISSUE THREAD

**Issue by nianshaoke** [wisp-x/lsky-pro#92]
最新版本没找到...

**Comment by wisp-x** [comment]
鼠标右键图片会看到重命名选项.

**Comment by nianshaoke** [comment]
> 鼠标右键图片会看到重命名选项。

弹出 property not exists:app\common\model\Users->user_id

**Comment by wisp-x** [comment]
是个 bug, 下个版本修复

**Comment by liufurusu** [comment]
> 是的无法修改，  可以改图片添加标签码/？图片多了那样好搜索！ 怎么样才可以做水印功能？

**Comment by liufurusu** [comment]
无法搜索出图片名字
