### ISSUE TITLE
图片列表无法用调用代码

### ISSUE THREAD

**Issue by liufurusu** [wisp-x/lsky-pro#93]
![微信截图_20200318120829](https://user-images.githubusercontent.com/12858489/76924430-38693180-6911-11ea-91b5-92f6578d5447.png)
无法调用代码  只有刚刚上传的才可以看

**Comment by wisp-x** [comment]
设计如此, 图片管理里只能复制链接

**Comment by liufurusu** [comment]
能添加这个功能吗 ，或者批量调用

**Comment by liufurusu** [comment]
可以帮我删除这条记录吗？
