### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by 616620131** [wisp-x/lsky-pro#94]
电脑端上传会出现500错误，手机不会。版本v1.58，nginx/1.17.9，php7.2.28
![8B6dat.png](https://s1.ax1x.com/2020/03/18/8B6dat.png)
浏览器控制台具体报错是POST https://域名/upload/upload.html 500

**Comment by wisp-x** [comment]
这似乎是环境的问题, 检查一下你的 nginx 配置

**Comment by 616620131** [comment]
不知道是不是环境，我在1.57版本以前一直都没问题，升级1.58之后，就有这种情况了

**Comment by 616620131** [comment]
找到问题了，nginx防火墙阻止了upload，谢谢
