### ISSUE TITLE
更新到1.6.0以后管理后台无法看到之前上传的图像

### ISSUE THREAD

**Issue by OuYanghaoyue** [wisp-x/lsky-pro#95]
更新到1.6.0以后管理后台无法看到之前上传的图像，但是之前的图片链接依然可以使用。

**Comment by wisp-x** [comment]
换一个普通用户, 使用该用户上传一下图片在切换一下管理员账户, 登录后台看一下能不能看到图片

**Comment by OuYanghaoyue** [comment]
你好 按照你的操作以后， 切换管理员账户可以看到图片
