### ISSUE TITLE
文件命名规则的{original}变量没有用

### ISSUE THREAD

**Issue by klpbbs** [wisp-x/lsky-pro#96]
就是原文件名的那个变量原文件名，没有用

**Comment by wisp-x** [comment]
{original} 命名规则时不支持与其他规则组合使用.

**Comment by wisp-x** [comment]
{original} 命名规则不支持与其他规则组合使用.

**Comment by klpbbs** [comment]
不能与其他的一起用，那重名了怎么办。QWQ，主要是因为没有原文件名，那个搜索很难搜到

**Comment by wisp-x** [comment]
重名就会被覆盖 QWQ, 可以给图片别名, 下次搜索直接搜别名即可

**Comment by nianshaoke** [comment]
> 重名就会被覆盖 QWQ, 可以给图片别名, 下次搜索直接搜别名即可

刚用最新版测试有点无敌啊...
![测试](https://raw.githubusercontent.com/nianshaoke/images/master/snipaste_20200319_213813.png)
