### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by wutong233** [wisp-x/lsky-pro#98]
能否在「我的图片」和「图片管理」中直接查看图片对应链接?否则第二次用链接不方便...

**Comment by wisp-x** [comment]
我的图片中是可以右键图片复制链接的

**Comment by Orange-Summer** [comment]
> 我的图片中是可以右键图片复制链接的

感觉这里做的提示不够明显吧，我找了半天才发现可以图片右键，因为选中一张图片以后上面出来一行选项会让人以为这就是所有可以交互的选项了，导致我都没有想到右键。
