### ISSUE TITLE
1.6 无法搜索文件名

### ISSUE THREAD

**Issue by liufurusu** [wisp-x/lsky-pro#99]
1.6 无法搜索文件名

**Comment by wisp-x** [comment]
测试可以通过文件名搜索, 请检查你的搜索关键字

**Comment by liufurusu** [comment]
![1](https://user-images.githubusercontent.com/12858489/77070336-00eba980-6a25-11ea-9604-05331df21b1d.png)
![2734](https://user-images.githubusercontent.com/12858489/77070343-021cd680-6a25-11ea-8172-dfb45d0e2bdf.png)

**Comment by liufurusu** [comment]
![1](https://user-images.githubusercontent.com/12858489/77070367-0ea12f00-6a25-11ea-8345-b49b8765b893.png)
![2734](https://user-images.githubusercontent.com/12858489/77070373-0fd25c00-6a25-11ea-976b-3f96ebbbee8e.png)
数字没有改名

**Comment by wisp-x** [comment]
文件命名使用的什么规则?

**Comment by liufurusu** [comment]
目录年月     原名不变！

**Comment by liufurusu** [comment]
目录{Y}{m}    文件命   {original}

**Comment by liufurusu** [comment]
https://img.uvtuku.com/202003/3397.jpg  
文件是有的！
是不是对数字搜索不好？

**Comment by wisp-x** [comment]
搜索框内检查一下是否有空格

**Comment by liufurusu** [comment]
![image](https://user-images.githubusercontent.com/12858489/77071204-99365e00-6a26-11ea-8d26-ad0e98b0d156.png)
我是用数字序号的    ，但是搜索就不出来那个图片

**Comment by liufurusu** [comment]
没有空格的！

**Comment by nianshaoke** [comment]
经测试，未复现
![521.png](https://cloud.nianshaoke.cn/202003/521.png)

**Comment by nianshaoke** [comment]
经测试，未复现
![测试](https://raw.githubusercontent.com/nianshaoke/images/master/521.png)

**Comment by liufurusu** [comment]
img.uvtuku.com   
admin
123123
你进入试试！！

**Comment by liufurusu** [comment]
搜索大一点数字就没有了！图出现了！

**Comment by wisp-x** [comment]
敏感信息请私信邮件

**Comment by wisp-x** [comment]
图片在分出多页的时候会出现这个情况, 是个 bug

**Comment by nianshaoke** [comment]
> 搜索大一点数字就没有了！图出现了！

确实，老哥你图片多就出现了，等作者修复吧😂

**Comment by liufurusu** [comment]
OK   我想也是应该多了 才出现问题！

**Comment by wisp-x** [comment]
目前的解决方法如下:
打开`application\index\view\user\images.html`文件, 在第 `473` 行插入新行, 内容:
```
params.page = 1;
```

https://github.com/wisp-x/lsky-pro/blob/6ba708143d43563fb52f170f8c8d8db9bb588196/application/index/view/user/images.html#L474

**Comment by liufurusu** [comment]
好的！ 谢谢
![image](https://user-images.githubusercontent.com/12858489/77079125-7f9b1380-6a32-11ea-8f9e-9a900bcdb576.png)
搜索了 ，还是出现一些不该出现的图片 。

**Comment by wisp-x** [comment]
搜索会不仅会匹配图片名称, 同时会匹配 md5 值, 你搜索 300 之所以出现多余的图片是因为匹配到 md5 值中有 300 关键字的图片, 想要精确一点的话, 尽量将搜索关键字补充完整即可.
